
-- 프로시저 ======================================================================

-- ○ 1. 회원가입 생성 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_SIGNUP
( P_USER_LOGIN_ID IN VARCHAR2
, P_USER_PASSWORD IN VARCHAR2
, P_USER_PASSWORD_CHECK IN VARCHAR2
, P_USER_NAME IN VARCHAR2
, P_USER_SSN IN CHAR
, P_USER_EMAIL IN VARCHAR2
, P_USER_PHONE IN CHAR
, P_USER_ZIPCODE IN VARCHAR2
, P_USER_ADDRESS IN VARCHAR2
, P_USER_ADDRESS_DETAIL IN VARCHAR2
)
IS
    V_HAS_ID NUMBER(1);
    V_HAS_SSN NUMBER(1);
    V_BIRTH DATE;
    V_AGE NUMBER(3);
    
    
    ERR_DUPLICATE_ID EXCEPTION;
    ERR_DUPLICATE_SSN EXCEPTION;
    ERR_INVALID_SSN EXCEPTION;
    ERR_INVALID_FORMAT_LENGTH EXCEPTION;
    ERR_UNDERAGE EXCEPTION;
    ERR_WRONG_PWD EXCEPTION;
    ERR_INVALID_EMAIL EXCEPTION;
    ERR_NULL_VALUE EXCEPTION;

BEGIN
-- NULL 검사
    IF (P_USER_LOGIN_ID IS NULL OR P_USER_PASSWORD IS NULL 
        OR P_USER_PASSWORD IS NULL OR P_USER_NAME IS NULL OR P_USER_SSN IS NULL
        OR P_USER_SSN IS NULL OR P_USER_EMAIL IS NULL OR P_USER_PHONE IS NULL
        OR P_USER_ZIPCODE IS NULL OR P_USER_ADDRESS IS NULL OR P_USER_ADDRESS_DETAIL IS NULL)   THEN
            RAISE ERR_NULL_VALUE;
    END IF;

-- 아이디 중복 검사
    SELECT COUNT(*) INTO V_HAS_ID
    FROM USER_ACCOUNT
    WHERE USER_LOGIN_ID = P_USER_LOGIN_ID;
    
    IF(V_HAS_ID != 0) THEN
        RAISE ERR_DUPLICATE_ID;
    END IF;
    
-- 아이디 조건 검사(4글자이상 12자이하)
    IF(LENGTH(P_USER_LOGIN_ID)<4 OR LENGTH(P_USER_LOGIN_ID)>12) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;

-- 비밀번호 조건 검사(8자이상 16자이하)
    IF(LENGTH(P_USER_PASSWORD)<8 OR LENGTH(P_USER_PASSWORD)>16) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;
    
-- 비밀번호 확인
    IF(P_USER_PASSWORD != P_USER_PASSWORD_CHECK) THEN
        RAISE ERR_WRONG_PWD;
    END IF;
    
-- 주민번호 유효성 검사
    IF NOT REGEXP_LIKE(P_USER_SSN, '^[0-9]{6}[1-4][0-9]{6}$') THEN
        RAISE ERR_INVALID_SSN;
    END IF;
    
-- 주민번호 중복 검사
    SELECT COUNT(*) INTO V_HAS_SSN
    FROM USER_PROFILE
    WHERE USER_SSN = P_USER_SSN;
    
    IF(V_HAS_SSN != 0) THEN
        RAISE ERR_DUPLICATE_SSN;
    END IF;

-- 주민번호 미성년자 제외 검사
    V_BIRTH := TO_DATE(
        CASE
            WHEN SUBSTR(P_USER_SSN,7,1) IN ('3','4') THEN '20'
            ELSE '19'
        END || SUBSTR(P_USER_SSN,1,6), 'YYYYMMDD'
    );

    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, V_BIRTH)/12);
    
    IF(V_AGE<19) THEN
        RAISE ERR_UNDERAGE;
    END IF;

-- 이메일 유효성 검사
    -- ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
     IF NOT REGEXP_LIKE(P_USER_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE ERR_INVALID_EMAIL;
    END IF;

-- 1. USERS INSERT
    INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL);
    
-- 2. USER_ACCOUNT INSERT
    INSERT INTO USER_ACCOUNT
    VALUES(USERS_SEQ.CURRVAL, P_USER_LOGIN_ID, P_USER_PASSWORD);

-- 3. USER_PROFILE INSERT
    INSERT INTO USER_PROFILE
    VALUES(USERS_SEQ.CURRVAL, P_USER_NAME, P_USER_SSN, P_USER_EMAIL, P_USER_PHONE
    , P_USER_ZIPCODE, P_USER_ADDRESS, P_USER_ADDRESS_DETAIL);
    

      
-- 4. ACCOUNT_EVENT_HISTORY INSERT
    INSERT INTO ACCOUNT_EVENT_HISTORY
    VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, USERS_SEQ.CURRVAL, 1, SYSDATE);

-- 예외 처리
    EXCEPTION 
        WHEN ERR_DUPLICATE_ID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 아이디입니다.');
        WHEN ERR_DUPLICATE_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 주민등록번호입니다.');
        WHEN ERR_INVALID_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, '유효하지 않은 주민등록번호입니다.');   
        WHEN ERR_INVALID_FORMAT_LENGTH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, '입력 범위가 맞지 않습니다.');
        WHEN ERR_UNDERAGE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20006, '미성년자입니다.'); 
        WHEN ERR_WRONG_PWD THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, '비밀번호가 일치하지 않습니다.'); 
        WHEN ERR_INVALID_EMAIL THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, '올바른 이메일 형식이 아닙니다.');
        WHEN ERR_NULL_VALUE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20014, '필수 입력 항목이 누락되었습니다.');
END;
/

-- ○ 2. 회원탈퇴 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_DELETE
( P_USER_ID IN USERS.USER_ID%TYPE
)
IS
     -- 커서 정의 (경매테이블)
     CURSOR CUR_USER_AUCTION IS
            SELECT AR.AUCTION_ID
            FROM AUCTION_REGISTRATION AR
                JOIN PRODUCT P 
            ON AR.PRODUCT_ID = P.PRODUCT_ID
            WHERE P.USER_ID = P_USER_ID;
            
    CURSOR CUR_USER_BID IS
        SELECT AR.AUCTION_ID
        FROM AUCTION_REGISTRATION AR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON ABP.AUCTION_ID = AR.AUCTION_ID
        WHERE ABP.USER_ID = P_USER_ID;

    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_BID_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    V_HAS_BID NUMBER;
    V_HAS_BID_2 NUMBER;
    V_PENALTY_SCORE    NUMBER;
    V_PENALTY_ID   PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_NAME USER_PROFILE.USER_NAME%TYPE;
    V_SSN USER_PROFILE.USER_SSN%TYPE; 
    V_PHONE USER_PROFILE.USER_PHONE%TYPE; 
    V_EMAIL USER_PROFILE.USER_EMAIL%TYPE;
    V_ZIPCODE USER_PROFILE.USER_ZIPCODE%TYPE; 
    V_ADDRESS USER_PROFILE.USER_ADDRESS%TYPE;
    V_DETAIL USER_PROFILE.USER_ADDRESS_DETAIL%TYPE;
    
    ERR_HAS_ACTIVE_AUCTION EXCEPTION;
    ERR_HAS_ACTIVE_BID EXCEPTION;
    ERR_HAS_ACTIVE_WINNING EXCEPTION;
    ERR_HAS_MONEY EXCEPTION;
    ERR_HAS_PENALTY EXCEPTION;
    
BEGIN
    -- 진행 중인 경매 검사
    
        OPEN CUR_USER_AUCTION;
        LOOP
            FETCH CUR_USER_AUCTION INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_AUCTION%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_AUCTION;
                RAISE ERR_HAS_ACTIVE_AUCTION;
            END IF;
        END LOOP;
        CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 입찰 검사
        -- 입찰 참여 테이블에서 USER_ID로 조회해서 나온 경매코드들로
        -- 그 경매코드가 진행중인지 검사
        
        OPEN CUR_USER_BID;
        LOOP
            FETCH CUR_USER_BID INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_BID%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_BID;
                RAISE ERR_HAS_ACTIVE_BID;
            END IF;
        END LOOP;
         CLOSE CUR_USER_BID;

        -- 진행 중인 낙찰 검사
            SELECT COUNT(*) INTO V_HAS_BID
            FROM AUCTION_WINNING_RESULT AWR
            JOIN AUCTION_BID_PARTICIPATION ABP ON AWR.BID_ID = ABP.BID_ID
            WHERE ABP.USER_ID = P_USER_ID
            AND AWR.BID_RESULT_ID NOT IN (SELECT BID_RESULT_ID FROM BID_FAILURE_HISTORY) -- 실패 이력 없고
            AND AWR.BID_RESULT_ID NOT IN ( -- 거래 완료 이력도 없는 것 카운트
                SELECT BID_RESULT_ID FROM AUCTION_WINNING_PAYMENT AWP
                JOIN DELIVERY_COMPLETED DC ON AWP.PAYMENT_ID = DC.PAYMENT_ID
                JOIN PURCHASE_CONFIRM_HISTORY PCH ON DC.SHIPPING_ID = PCH.SHIPPING_ID
                JOIN TRANSACTION_COMPLETED TC ON PCH.PURCHASE_CONFIRM_ID = TC.PURCHASE_CONFIRM_ID);

            IF V_HAS_BID > 0 THEN
                RAISE ERR_HAS_ACTIVE_WINNING;
            END IF;
        
    -- 잔여머니가 있는지
        IF (FN_GET_USER_MONEY_BALANCE(P_USER_ID)>0) THEN
            RAISE ERR_HAS_MONEY;
        END IF;
    
    -- 회원의 상태가 영구정지 상태인지
        SELECT NVL(SUM(PENALTY_SCORE), 0) INTO V_PENALTY_SCORE
        FROM PENALTY_HISTORY
        WHERE USER_ID = P_USER_ID
        AND PENALTY_ID NOT IN (SELECT PENALTY_ID FROM PENALTY_CANCEL);

        IF V_PENALTY_SCORE >= 4 THEN
            RAISE ERR_HAS_PENALTY;
        END IF;

    
    -- USER_PROFILE 조회
        SELECT USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
        , USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL 
        INTO V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- DELETED_USER INSERT
        INSERT INTO DELETED_USER(USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
        VALUES(P_USER_ID, V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL);
    
    -- USER_PROFILE DELETE
        DELETE
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- ACCOUNT_EVENT_HISTORY INSERT
        INSERT INTO ACCOUNT_EVENT_HISTORY
        VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, P_USER_ID, 2, SYSDATE);
    
    EXCEPTION
        WHEN ERR_HAS_ACTIVE_AUCTION THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
        WHEN ERR_HAS_ACTIVE_BID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20026, '진행 중인 입찰이 존재합니다.');
        WHEN ERR_HAS_ACTIVE_WINNING THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20027, '진행 중인 낙찰이 존재합니다.');
        WHEN ERR_HAS_PENALTY THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20028, '영구정지 회원은 탈퇴가 불가능합니다.');
        WHEN ERR_HAS_MONEY THEN   
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20029, '잔여머니가 존재합니다.');
    
END;
/

-- ○ 3. 상품 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRODUCT_INSERT
(
      P_USER_ID              IN PRODUCT.USER_ID%TYPE              -- 회원고유키 (NN)
    , P_PRODUCT_RELEASE_NAME IN PRODUCT.PRODUCT_RELEASE_NAME%TYPE -- 상품 발매명
    , P_PRODUCT_ALIAS        IN PRODUCT.PRODUCT_ALIAS%TYPE        -- 상품 별칭
    , P_MANUFACTURER_ID      IN PRODUCT.MANUFACTURER_ID%TYPE      -- 제조사 코드
    , P_PRODUCT_GRADE_ID     IN PRODUCT.PRODUCT_GRADE_ID%TYPE     -- 등급 코드 (NN)
    , P_PRODUCT_GENRE_ID     IN PRODUCT.PRODUCT_GENRE_ID%TYPE     -- 장르 코드 (NN)
    , P_PRODUCT_SIZE_ID      IN PRODUCT.PRODUCT_SIZE_ID%TYPE      -- 사이즈 코드 (NN)
    , P_WORK_NAME            IN PRODUCT.WORK_NAME%TYPE            -- 작품명
    , P_CHARACTER_NAME       IN PRODUCT.CHARACTER_NAME%TYPE       -- 캐릭터명
    , P_PURCHASE_DATETIME    IN PRODUCT.PURCHASE_DATETIME%TYPE    -- 구매일시
    , P_IS_OPENED            IN PRODUCT.IS_OPENED%TYPE            -- 개봉여부 (NN)
    , P_IS_PARTS_MISSING     IN PRODUCT.IS_PARTS_MISSING%TYPE     -- 파츠 누락 여부 (NN)
    , P_DESCRIPTIONS         IN PRODUCT.DESCRIPTIONS%TYPE         -- 상세설명
    , P_IMAGE_PATH_1         IN PRODUCT.IMAGE_PATH_1%TYPE         -- 이미지 1 (NN)
    , P_IMAGE_PATH_2         IN PRODUCT.IMAGE_PATH_2%TYPE         -- 이미지 2 (NN)
    , P_IMAGE_PATH_3         IN PRODUCT.IMAGE_PATH_3%TYPE         -- 이미지 3 (NN)
    , P_IS_PUBLIC            IN PRODUCT.IS_PUBLIC%TYPE            -- 공개 여부 (NN)
)
IS
    V_CNT NUMBER;
BEGIN
   
    -- 회원 정보 체크
    IF P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20010, '회원 정보가 유효하지 않습니다.');
    END IF;

    -- 선택사항 체크
    IF P_PRODUCT_GRADE_ID IS NULL OR P_PRODUCT_GENRE_ID IS NULL OR P_PRODUCT_SIZE_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, '상품 등급, 장르, 사이즈는 필수 선택 사항입니다.');
    END IF;

    -- 상태 및 공개 여부 체크
    IF P_IS_OPENED IS NULL OR P_IS_PARTS_MISSING IS NULL OR P_IS_PUBLIC IS NULL THEN
        RAISE_APPLICATION_ERROR(-20012, '개봉/누락/공개 여부를 모두 선택해주세요.');
    END IF;

    -- 이미지 3장 필수 체크
    IF P_IMAGE_PATH_1 IS NULL OR P_IMAGE_PATH_2 IS NULL OR P_IMAGE_PATH_3 IS NULL THEN
        RAISE_APPLICATION_ERROR(-20013, '상품 사진은 최소 3장이 필요합니다.');
    END IF;

    INSERT INTO PRODUCT 
    (
          PRODUCT_ID,           USER_ID,              PRODUCT_RELEASE_NAME
        , PRODUCT_ALIAS,        MANUFACTURER_ID,      PRODUCT_GRADE_ID
        , PRODUCT_GENRE_ID,     PRODUCT_SIZE_ID,      WORK_NAME
        , CHARACTER_NAME,       PURCHASE_DATETIME,    IS_OPENED
        , IS_PARTS_MISSING,     DESCRIPTIONS,         IMAGE_PATH_1
        , IMAGE_PATH_2,         IMAGE_PATH_3,         IS_PUBLIC
        , CREATED_AT
    ) VALUES 
    (
          PRODUCT_SEQ.NEXTVAL,  P_USER_ID,            P_PRODUCT_RELEASE_NAME
        , P_PRODUCT_ALIAS,      P_MANUFACTURER_ID,    P_PRODUCT_GRADE_ID
        , P_PRODUCT_GENRE_ID,   P_PRODUCT_SIZE_ID,    P_WORK_NAME
        , P_CHARACTER_NAME,     P_PURCHASE_DATETIME,  P_IS_OPENED
        , P_IS_PARTS_MISSING,   P_DESCRIPTIONS,       P_IMAGE_PATH_1
        , P_IMAGE_PATH_2,       P_IMAGE_PATH_3,       P_IS_PUBLIC
        , SYSDATE
    );
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, '상품등록이 실패하였습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ○ 4. 상품 수정 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRODUCT_UPDATE
(
      P_PRODUCT_ID           IN PRODUCT.PRODUCT_ID%TYPE           -- 상품코드 (PK)
    , P_USER_ID              IN PRODUCT.USER_ID%TYPE              -- 본인 확인용
    , P_PRODUCT_RELEASE_NAME IN PRODUCT.PRODUCT_RELEASE_NAME%TYPE -- 상품 발매명
    , P_PRODUCT_ALIAS        IN PRODUCT.PRODUCT_ALIAS%TYPE        -- 상품 별칭
    , P_MANUFACTURER_ID      IN PRODUCT.MANUFACTURER_ID%TYPE      -- 제조사 코드
    , P_PRODUCT_GRADE_ID     IN PRODUCT.PRODUCT_GRADE_ID%TYPE     -- 등급 코드 (NN)
    , P_PRODUCT_GENRE_ID     IN PRODUCT.PRODUCT_GENRE_ID%TYPE     -- 장르 코드 (NN)
    , P_PRODUCT_SIZE_ID      IN PRODUCT.PRODUCT_SIZE_ID%TYPE      -- 사이즈 코드 (NN)
    , P_WORK_NAME            IN PRODUCT.WORK_NAME%TYPE            -- 작품명
    , P_CHARACTER_NAME       IN PRODUCT.CHARACTER_NAME%TYPE       -- 캐릭터명
    , P_PURCHASE_DATETIME    IN PRODUCT.PURCHASE_DATETIME%TYPE    -- 구매일시
    , P_IS_OPENED            IN PRODUCT.IS_OPENED%TYPE            -- 개봉여부 (NN)
    , P_IS_PARTS_MISSING     IN PRODUCT.IS_PARTS_MISSING%TYPE     -- 파츠 누락 여부 (NN)
    , P_DESCRIPTIONS         IN PRODUCT.DESCRIPTIONS%TYPE         -- 상세설명
    , P_IMAGE_PATH_1         IN PRODUCT.IMAGE_PATH_1%TYPE         -- 이미지 1 (NN)
    , P_IMAGE_PATH_2         IN PRODUCT.IMAGE_PATH_2%TYPE         -- 이미지 2 (NN)
    , P_IMAGE_PATH_3         IN PRODUCT.IMAGE_PATH_3%TYPE         -- 이미지 3 (NN)
    , P_IS_PUBLIC            IN PRODUCT.IS_PUBLIC%TYPE            -- 공개 여부 (NN)
)
IS
    V_CNT NUMBER;
BEGIN
   
    -- 상품 정보 체크
    IF P_PRODUCT_ID IS NULL OR P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20023, 'ERR_ID_REQUIRED');
    END IF;


    -- 선택사항 체크
    IF P_PRODUCT_GRADE_ID IS NULL OR P_PRODUCT_GENRE_ID IS NULL OR P_PRODUCT_SIZE_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, '상품의 등급, 장르, 사이즈 정보는 필수입니다.');
    END IF;
    
    -- 상태 및 공개 여부 체크
    IF P_IS_OPENED IS NULL OR P_IS_PARTS_MISSING IS NULL OR P_IS_PUBLIC IS NULL THEN
        RAISE_APPLICATION_ERROR(-20012, '개봉 여부, 파츠 누락 여부, 공개 설정은 필수 선택 사항입니다.');
    END IF;
    
    -- 이미지 3장 필수 체크
    IF P_IMAGE_PATH_1 IS NULL OR P_IMAGE_PATH_2 IS NULL OR P_IMAGE_PATH_3 IS NULL THEN
        RAISE_APPLICATION_ERROR(-20013, '이미지 3장은 필수 항목입니다.');
    END IF;

    -- 상품 존재 및 본인 소유 여부 확인
    SELECT COUNT(*) INTO V_CNT
    FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID AND USER_ID = P_USER_ID;

    IF V_CNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20021, '해당 상품이 없거나 수정 권한이 없습니다.');
    END IF;

    UPDATE PRODUCT
    SET PRODUCT_RELEASE_NAME = P_PRODUCT_RELEASE_NAME, PRODUCT_ALIAS = P_PRODUCT_ALIAS,   MANUFACTURER_ID    = P_MANUFACTURER_ID
     , PRODUCT_GRADE_ID     = P_PRODUCT_GRADE_ID,    PRODUCT_GENRE_ID = P_PRODUCT_GENRE_ID, PRODUCT_SIZE_ID  = P_PRODUCT_SIZE_ID
     , WORK_NAME            = P_WORK_NAME,           CHARACTER_NAME   = P_CHARACTER_NAME,   PURCHASE_DATETIME= P_PURCHASE_DATETIME
     , IS_OPENED            = P_IS_OPENED,           IS_PARTS_MISSING = P_IS_PARTS_MISSING, DESCRIPTIONS     = P_DESCRIPTIONS
     , IMAGE_PATH_1         = P_IMAGE_PATH_1,        IMAGE_PATH_2     = P_IMAGE_PATH_2,     IMAGE_PATH_3     = P_IMAGE_PATH_3
     , IS_PUBLIC            = P_IS_PUBLIC
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20022, '수정 대상이 존재하지 않습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/


-- ○ 5. 상품 삭제 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRODUCT_DELETE
(
      P_PRODUCT_ID IN PRODUCT.PRODUCT_ID%TYPE 
    , P_USER_ID    IN PRODUCT.USER_ID%TYPE  
)
IS
    V_CNT NUMBER;
BEGIN
    -- 파라미터 체크
    IF P_PRODUCT_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20023, '삭제할 상품 번호가 입력되지 않았습니다.');
    END IF;
    
    IF P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20010, '회원 정보가 유효하지 않습니다.');
    END IF;

    -- 상품 존재 및 본인 여부 확인
    SELECT COUNT(*) INTO V_CNT
    FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID AND USER_ID = P_USER_ID;

    IF V_CNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20024, '삭제 권한이 없거나 이미 존재하지 않는 상품입니다.');
    END IF;

    -- 진행 중인 경매 여부 확인 (함수 FN_IS_AUCTION_FINISHED 활용)
    -- 해당 상품으로 등록된 경매들 중, 함수 결과 0 = 경매중
    SELECT COUNT(*) INTO V_CNT
    FROM AUCTION_REGISTRATION
    WHERE PRODUCT_ID = P_PRODUCT_ID
      AND FN_IS_AUCTION_FINISHED(AUCTION_ID) = 0; 

    IF V_CNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
    END IF;

    -- 이미지 테이블 삭제
    DELETE FROM PRODUCT_IMAGE
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    -- 상품 삭제
    DELETE FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20025, '삭제 대상이 존재하지 않습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


-- ○ 6. 경매 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUCTION_CREATE(
    P_USER_ID           IN NUMBER,              --회원 고유키
    P_PRODUCT_ID        IN NUMBER,              --상품코드
    P_AUCTION_TITLE     IN VARCHAR2,            --경매제목
    P_CONTENT           IN VARCHAR2,            --경매 글
    P_START_PRICE       IN NUMBER,              --시작가
    P_PERIOD_CODE       IN NUMBER               --경매기간
)
IS
    ERR_LACK_MONEY      CONSTANT NUMBER := -20004;
    ERR_UNKNOWN         CONSTANT NUMBER := -20009;

    V_CURRENT_MONEY     NUMBER := 0;
    V_AUCTION_ID        NUMBER;
BEGIN
    
    -- [수정된 부분] 직접 만든 잔액 조회 함수를 사용합니다.
    V_CURRENT_MONEY := FN_GET_USER_MONEY_BALANCE(P_USER_ID);

    -- 보증금 부족할 시 (함수 에러 -1 포함)
    IF V_CURRENT_MONEY < 30000 THEN
        RAISE_APPLICATION_ERROR(ERR_LACK_MONEY, '보증금이 부족합니다. 현재 잔액: ' || V_CURRENT_MONEY);
    END IF;

    -- 경매 등록 테이블 INSERT
    INSERT INTO AUCTION_REGISTRATION (
        AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, 
        START_PRICE, CREATED_AT, AUCTION_PERIOD_ID
    ) VALUES (
        AUCTION_SEQ.NEXTVAL, P_PRODUCT_ID, P_AUCTION_TITLE, 
        P_CONTENT, P_START_PRICE, SYSDATE, P_PERIOD_CODE
    ) RETURNING AUCTION_ID INTO V_AUCTION_ID;

    -- 머니 차감 기록 INSERT (차감은 HISTORY 테이블에만 기록)
    INSERT INTO MONEY_TRANSACTION_HISTORY (
        MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
    ) VALUES (
        MONEY_TRANSACTION_SEQ.NEXTVAL, P_USER_ID, 2, V_AUCTION_ID, -30000, SYSDATE
    );
    COMMIT;

EXCEPTION        
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; 
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류 발생: ' || SQLERRM);
        END IF;
END;

-- ○ 7. 경매 취소 프로시저 
CREATE OR REPLACE PROCEDURE PRC_AUCTION_CANCEL(
    P_AUCTION_ID    NUMBER,
    P_USER_ID       NUMBER,
    P_CANCEL_REASON VARCHAR2
)
IS
    V_PENALTY_ID      NUMBER;
    V_TOTAL_SCORE     NUMBER := 0;
    V_END_DATE        DATE;        -- 정지 종료일
    
    CURSOR BIDDER_LIST IS
        SELECT DISTINCT USER_ID FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = P_AUCTION_ID;
     
    ERR_UNKNOWN         CONSTANT NUMBER := -20009; 
        
BEGIN
    -- 1. 입찰자 전원 보증금 환급 
    FOR R IN BIDDER_LIST LOOP
        INSERT INTO MONEY_TRANSACTION_HISTORY (
            MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
        ) VALUES (
            MONEY_TRANSACTION_SEQ.NEXTVAL, R.USER_ID, 5, P_AUCTION_ID, 30000, SYSDATE
        );
    END LOOP;

    -- 2. 판매자 보증금 몰수 기록
    INSERT INTO MONEY_TRANSACTION_HISTORY (
        MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
    ) VALUES (
        MONEY_TRANSACTION_SEQ.NEXTVAL, P_USER_ID, 7, P_AUCTION_ID, 0, SYSDATE
    );
    
    -- 3. 패널티 점수 계산 로직 (누적 점수 - 취소 점수)
    SELECT (
        (SELECT NVL(SUM(PENALTY_SCORE), 0) FROM PENALTY_HISTORY WHERE USER_ID = P_USER_ID) -
        (SELECT NVL(SUM(PH.PENALTY_SCORE), 0) 
         FROM PENALTY_CANCEL PC 
         JOIN PENALTY_HISTORY PH ON PC.PENALTY_ID = PH.PENALTY_ID 
         WHERE PH.USER_ID = P_USER_ID)
    ) INTO V_TOTAL_SCORE FROM DUAL;

    V_TOTAL_SCORE := V_TOTAL_SCORE + 1;

    -- 4. 패널티 단계별 정지 종료일 설정
    IF V_TOTAL_SCORE = 1 THEN
        V_END_DATE := SYSDATE; 
    ELSIF V_TOTAL_SCORE = 2 THEN
        V_END_DATE := SYSDATE + 7;
    ELSIF V_TOTAL_SCORE = 3 THEN
        V_END_DATE := SYSDATE + 30;
    ELSE
        V_END_DATE := TO_DATE('9999-12-31', 'YYYY-MM-DD');
    END IF;

    -- 5. 패널티 이력 INSERT
    V_PENALTY_ID := PENALTY_SEQ.NEXTVAL;
    INSERT INTO PENALTY_HISTORY (
        PENALTY_ID, USER_ID, PENALTY_TYPE_ID, ADMIN_ACCOUNT_ID, PENALTY_SCORE, CREATED_AT
    ) VALUES (
        V_PENALTY_ID, P_USER_ID, 1, NULL, 1, SYSDATE 
    );

    -- 6. 패널티 상태 기록
    INSERT INTO PENALTY_STATUS (
        PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE
    ) VALUES (
        PENALTY_STATUS_SEQ.NEXTVAL, V_PENALTY_ID, SYSDATE, V_END_DATE
    );

    -- 7. 경매 취소 이력 기록
    INSERT INTO AUCTION_CANCEL_HISTORY (
        AUCTION_CANCEL_ID, AUCTION_ID, CANCEL_REASON, CANCEL_AT
    ) VALUES (
        AUCTION_CANCEL_SEQ.NEXTVAL, P_AUCTION_ID, P_CANCEL_REASON, SYSDATE
    );

    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF;
END;
/


-- ○ 8. 입찰 생성 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUCTION_BID_CREATE
(
    P_AUCTION_ID   IN NUMBER
  , P_USER_ID      IN NUMBER  
  , P_BID_PRICE    IN NUMBER
  , P_RESULT       OUT VARCHAR2
)
IS
    V_SELLER_ID      NUMBER;
    V_CURRENT_PRICE  NUMBER;
    V_USER_MONEY     NUMBER;
    V_MAX_PRICE      NUMBER; 
    V_MY_BID_COUNT   NUMBER; 
    V_CANCEL_COUNT   NUMBER; 
    V_TOP_BIDDER_ID  NUMBER := 0; -- 최고가 입찰자 ID 담을 변수
BEGIN
    -- 1. 경매 취소 여부 확인
    SELECT COUNT(*) INTO V_CANCEL_COUNT
    FROM AUCTION_CANCEL_HISTORY
    WHERE AUCTION_ID = P_AUCTION_ID;

    IF V_CANCEL_COUNT > 0 THEN
        P_RESULT := '이미 취소된 경매에는 입찰할 수 없습니다.';
        RETURN;
    END IF;

    -- 2. 본인 경매 입찰 방지
    SELECT USER_ID INTO V_SELLER_ID 
    FROM PRODUCT
    WHERE PRODUCT_ID = (SELECT PRODUCT_ID
                        FROM AUCTION_REGISTRATION 
                        WHERE AUCTION_ID = P_AUCTION_ID);
                        
    IF V_SELLER_ID = P_USER_ID THEN
        P_RESULT := '본인이 등록한 경매에는 입찰할 수 없습니다.';
        RETURN;
    END IF;
    
    -- 3. 본인 연속 추가 입찰 방지 (수정된 부분)
    BEGIN
        SELECT USER_ID INTO V_TOP_BIDDER_ID
        FROM (
            SELECT USER_ID, RANK() OVER (ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
            FROM AUCTION_BID_PARTICIPATION
            WHERE AUCTION_ID = P_AUCTION_ID
        )
        WHERE RK = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN V_TOP_BIDDER_ID := 0; -- 첫 입찰인 경우
    END;

    IF V_TOP_BIDDER_ID = P_USER_ID THEN
       P_RESULT := '현재 귀하가 최고가 입찰자입니다. 연속 입찰은 불가능합니다.';
       RETURN;
    END IF;

    -- 4. 현재 입찰가 조회 및 유효성 검사
    V_CURRENT_PRICE := FN_GET_AUCTION_CURRENT_PRICE(P_AUCTION_ID);

    IF P_BID_PRICE <= V_CURRENT_PRICE THEN
        P_RESULT := '현재가(' || V_CURRENT_PRICE || '원)보다 높은 금액을 입력해야 합니다.';
        RETURN; 
    END IF;
    
    -- 5. 경매 입찰 상한가 검사
    V_MAX_PRICE := FN_GET_BID_MAX_LIMIT(P_AUCTION_ID); 

    IF P_BID_PRICE > V_MAX_PRICE THEN
        P_RESULT := '상한가(' || V_MAX_PRICE || '원)를 초과하여 입찰할 수 없습니다.';
        RETURN;
    END IF;

    -- 6. 동시 입찰 제한 체크 (최대 10회)
    IF FN_GET_ACTIVE_BID_COUNT(P_USER_ID) >= 10 THEN 
        P_RESULT := '동시에 참여 가능한 경매 횟수 10회를 초과했습니다.';
        RETURN;
    END IF;
    
    -- 7. 신규 참여 여부 확인 및 보증금 차감
    SELECT COUNT(*) INTO V_MY_BID_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID AND USER_ID = P_USER_ID;

    IF V_MY_BID_COUNT = 0 THEN
        V_USER_MONEY := FN_GET_USER_MONEY_BALANCE(P_USER_ID);
        
        IF V_USER_MONEY < 30000 THEN
           P_RESULT := '보증금(30,000원) 결제를 위한 머니가 부족합니다.';
           RETURN;
        END IF;

        INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
        VALUES (MONEY_TRANSACTION_SEQ.NEXTVAL, P_USER_ID, 3, P_AUCTION_ID, -30000, SYSDATE); 
    END IF;

    -- 8. 입찰 기록 삽입
    INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, AUCTION_ID, USER_ID, BID_TIME, BID_PRICE)
    VALUES (BID_SEQ.NEXTVAL, P_AUCTION_ID, P_USER_ID, SYSTIMESTAMP, P_BID_PRICE);

    P_RESULT := 'SUCCESS';
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_RESULT := '에러 발생: ' || SQLERRM; -- 구체적인 에러 메시지 확인용
END;




-- ○ 9. 경매 마감 및 낙찰 처리 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUCTION_CLOSE
(
    P_AUCTION_ID IN  NUMBER
  , P_RESULT     OUT VARCHAR2
)
IS
    V_BID_COUNT      NUMBER;
    V_WINNER_BID_ID  NUMBER;
BEGIN

    -- 해당 경매의 입찰 참여 인원 확인
    SELECT COUNT(*) INTO V_BID_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    --  입찰자가 없는 경우 유찰
    IF V_BID_COUNT = 0 THEN
        P_RESULT := '해당 경매가 유찰되었습니다';
        
    -- 입찰자가 있는 경우(낙찰 처리)
    ELSE
    
        -- 최고가 입찰자가 2명 이상일 경우 입찰 시간이 빠른 순서
        SELECT BID_ID INTO V_WINNER_BID_ID
        FROM (
            SELECT BID_ID
            FROM AUCTION_BID_PARTICIPATION
            WHERE AUCTION_ID = P_AUCTION_ID
            ORDER BY BID_PRICE DESC, BID_TIME ASC
        )
        WHERE ROWNUM = 1;

        -- 낙찰 결과 테이블 삽입
        INSERT INTO AUCTION_WINNING_RESULT 
        (
            BID_RESULT_ID
           ,BID_ID
           ,CREATED_AT
        ) VALUES 
        (
            BID_RESULT_SEQ.NEXTVAL
           ,V_WINNER_BID_ID
           ,SYSDATE
        );

        P_RESULT := '낙찰 성공!!';
    END IF;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_RESULT := '존재하지 않는 경매입니다.';
    WHEN OTHERS THEN
        ROLLBACK;
        P_RESULT := 'ERROR:';
END;
/


-- ○ 10. 낙찰 결제 프로시저
-- 낙찰 결제 프로시저(컴파일O,테스트O)
CREATE OR REPLACE PROCEDURE PRC_WINNING_PAYMENT_CREATE
(
    V_USER_ID USERS.USER_ID%TYPE
    ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
    ,V_AMOUNT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE
)
AS
    N_BID_ID AUCTION_WINNING_RESULT.BID_ID%TYPE;
    N_AUCTION_ID AUCTION_BID_PARTICIPATION.AUCTION_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;
    N_MONEY_TYPE MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;

    N_AUCTION_PERIOD_ID AUCTION_PERIOD.AUCTION_PERIOD_ID%TYPE;
    N_AUCTION_PERIOD_NAME AUCTION_PERIOD.AUCTION_PERIOD_NAME%TYPE;
    
    N_END_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    N_START_PRICE AUCTION_REGISTRATION.START_PRICE%TYPE;
    
    N_AUCTION_PRICE AUCTION_BID_PARTICIPATION.BID_PRICE%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
BEGIN
 
    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT AUCTION_ID,USER_ID INTO N_AUCTION_ID,N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT CREATED_AT,AUCTION_PERIOD_ID,START_PRICE INTO N_CREATE_AT,N_AUCTION_PERIOD_ID,N_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = N_AUCTION_ID;
    
    SELECT AUCTION_PERIOD_NAME INTO N_AUCTION_PERIOD_NAME
    FROM AUCTION_PERIOD
    WHERE AUCTION_PERIOD_ID = N_AUCTION_PERIOD_ID;
    
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'일','');
    
    N_END_CREATE_AT := N_CREATE_AT + TO_NUMBER(TRIM(N_AUCTION_PERIOD_NAME)) + 1;
    
    IF(N_END_CREATE_AT < SYSTIMESTAMP)
        THEN RAISE NEW_ERR;
    END IF;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID
    ,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID
    ,N_MONEY_TYPE,N_AUCTION_ID,V_AMOUNT);
    
    INSERT INTO AUCTION_WINNING_PAYMENT(PAYMENT_ID
    ,BID_RESULT_ID,MONEY_ID)
    VALUES(PAYMENT_SEQ.NEXTVAL,V_RESULT_ID
    ,MONEY_TRANSACTION_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20100,'결제기간이 마감되어 결제가 불가능합니다');
        
        WHEN NEW_ERR1
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;
/


-- ○ 11. 구매 확정 및 거래 완료 프로시저 -- 안돌아감 
CREATE OR REPLACE PROCEDURE PRC_PURCHASE_CONFIRM
(
    V_USER_ID USERS.USER_ID%TYPE
    ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
)
IS
    N_PAYMENT_ID AUCTION_WINNING_PAYMENT.PAYMENT_ID%TYPE;
    N_SHIPPING_ID DELIVERY_COMPLETED.SHIPPING_ID%TYPE;
    
    N_BID_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;  -- 구매자 검증 아이디

    N_USER_ID2 USERS.USER_ID%TYPE; -- 판매자 아이디

    N_MONEY_TYPE1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE5 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE6 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
    NEW_ERR2 EXCEPTION;
BEGIN
    
    
    SELECT NVL(PAYMENT_ID,0) INTO N_PAYMENT_ID
    FROM AUCTION_WINNING_PAYMENT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_PAYMENT_ID = 0)
        THEN RAISE NEW_ERR;
    END IF;
    
    SELECT NVL(SHIPPING_ID,0) INTO N_SHIPPING_ID
    FROM DELIVERY_COMPLETED
    WHERE PAYMENT_ID = N_PAYMENT_ID;
    
    IF(N_SHIPPING_ID = 0)
        THEN RAISE NEW_ERR2;
    END IF;

    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT USER_ID INTO N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;

    -- 구매 확정
    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    VALUES(PURCHASE_CONFIRM_SEQ.NEXTVAL,N_SHIPPING_ID);
    
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE5
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE6
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금';
    
    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_MONEY_TYPE3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;
    
    IF(N_MONEY_TYPE5 = 0)
        THEN RAISE_APPLICATION_ERROR(-20112,'머니 분류 테이블에 "결제" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE6 = 0)
        THEN RAISE_APPLICATION_ERROR(-20113,'머니 분류 테이블에 "결제 대금" 코드명이 존재하지 않습니다');
    END IF;

    -- 구매자 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE1,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE3;

    -- 판매자 아이디
    SELECT USER_ID INTO N_USER_ID2
    FROM AUCTION_REGISTRATION A JOIN PRODUCT B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE AUCTION_ID = N_AUCTION_ID;

    -- 판매자 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE2,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = N_USER_ID2
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE4; 
    
    -- 구매대금 판매자에게 이력추가 V_USER_ID
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,N_USER_ID2,N_MONEY_TYPE_ID6,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = V_USER_ID
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID5;
    
    -- 거래완료 
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    VALUES(TRANSACTION_SEQ.NEXTVAL,PURCHASE_CONFIRM_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20102,'입금되지않은 낙찰입니다.');

        WHEN NEW_ERR1
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        -- (구매확정)결제자 와 (낙찰)입찰자
        
        WHEN NEW_ERR2
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'발송되지않은 낙찰입니다.');

        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;
/


-- ○ 13. 신고 접수 프로시저
CREATE OR REPLACE PROCEDURE PRC_REPORT_CREATE (
    P_USER_ID        NUMBER,         -- 신고자 ID
    P_REPORT_TYPE    NUMBER,         -- 도배 광고 개인정보기재 기타 1 2 3 4
    P_TARGET_ID      NUMBER,         -- 상품코드 혹은 경매코드 (예: 6)
    P_TARGET_TYPE    NUMBER,         -- 상품(1) OR 경매(2)     
    P_REPORT_REASON  VARCHAR2        -- 신고 사유
)
IS
    V_NEW_REPORT_ID  NUMBER;    -- 새롭게 생성된 신고신청코드
    V_EXIST_COUNT    NUMBER := 0; -- 중복 신고 확인용
    
    ERR_DUPLICATE    CONSTANT NUMBER := -20020; -- 중복 신고 에러 코드
    ERR_UNKNOWN      CONSTANT NUMBER := -20009;
BEGIN
    -- 1. 중복 신고 방지 로직 추가
    IF P_TARGET_TYPE = 1 THEN
        -- 동일 유저가 동일 상품을 신고했는지 확인
        SELECT COUNT(*) INTO V_EXIST_COUNT
        FROM REPORT_SUBMISSION RS
        JOIN PRODUCT_REPORT PR ON RS.REPORT_SUBMISSION_ID = PR.REPORT_SUBMISSION_ID
        WHERE RS.USER_ID = P_USER_ID 
          AND PR.PRODUCT_ID = P_TARGET_ID;
          
    ELSIF P_TARGET_TYPE = 2 THEN
        -- 동일 유저가 동일 경매를 신고했는지 확인
        SELECT COUNT(*) INTO V_EXIST_COUNT
        FROM REPORT_SUBMISSION RS
        JOIN AUCTION_REPORT AR ON RS.REPORT_SUBMISSION_ID = AR.REPORT_SUBMISSION_ID
        WHERE RS.USER_ID = P_USER_ID 
          AND AR.AUCTION_ID = P_TARGET_ID;
    END IF;

    IF V_EXIST_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(ERR_DUPLICATE, '이미 해당 대상에 대해 신고를 접수하셨습니다.');
    END IF;

    -- 2. 신고 신청(부모) INSERT
    V_NEW_REPORT_ID := REPORT_SEQ.NEXTVAL;
    
    INSERT INTO REPORT_SUBMISSION(
        REPORT_SUBMISSION_ID, USER_ID, REPORT_TARGET_ID, REPORT_TYPE_ID, REPORT_REASON, CREATED_AT)
    VALUES(V_NEW_REPORT_ID, P_USER_ID, P_TARGET_TYPE, P_REPORT_TYPE, P_REPORT_REASON, SYSDATE);
    
    -- 3. 신고 대상(상품, 경매) 분기 처리 후 해당 테이블 INSERT
    IF P_TARGET_TYPE = 1 THEN 
        INSERT INTO PRODUCT_REPORT(
          PRODUCT_REPORT_ID, REPORT_SUBMISSION_ID, PRODUCT_ID)
        VALUES(
          PRODUCT_REPORT_SEQ.NEXTVAL, V_NEW_REPORT_ID, P_TARGET_ID);
    
    ELSIF P_TARGET_TYPE = 2 THEN
        INSERT INTO AUCTION_REPORT(
          AUCTION_REPORT_ID, REPORT_SUBMISSION_ID, AUCTION_ID)
        VALUES(
          AUCTION_REPORT_SEQ.NEXTVAL, V_NEW_REPORT_ID, P_TARGET_ID);
    END IF;
    
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN     
        ROLLBACK;
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; 
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다: ' || SQLERRM);
        END IF; 
END;
/


-- ○ 15. 패널티 부여 프로시저
CREATE OR REPLACE PROCEDURE PRC_PENALTY_ASSIGN
( P_USER_ID             IN      USERS.USER_ID%TYPE
, P_ADMIN_ACCOUNT_ID    IN      ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, P_PENALTY_TYPE_ID     IN      PENALTY_HISTORY.PENALTY_SCORE%TYPE
, P_PENALTY_SCORE       IN      PENALTY_HISTORY.PENALTY_SCORE%TYPE
)
IS
	V_FLAG_ACTIVE_USER			CHAR(1);
	V_FLAG_BANNED_USER			CHAR(1);

    V_PENALTY_ID                PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_TOTAL_PENALTY_SCORE       PENALTY_HISTORY.PENALTY_SCORE%TYPE;
    V_PENALTY_END_DATE          PENALTY_STATUS.PENALTY_END_DATE%TYPE;
    
    ERR_PENALTY_TO_DEACTIVATED_USER EXCEPTION;
    ERR_PENALTY_TO_BANNED_USER EXCEPTION;
BEGIN
	-- 회원 유효성 체크) 활동 회원인지 확인
	SELECT
		CASE WHEN EXISTS(SELECT 1 FROM USER_PROFILE WHERE USER_ID = P_USER_ID)
		     THEN 'Y'
		     
		     ELSE 'N'
		END INTO V_FLAG_ACTIVE_USER
	FROM DUAL;

	-- 활동하지 않는 회원이라면(=탈퇴한 회원이라면) 예외 발생 처리
	IF V_FLAG_ACTIVE_USER = 'N' THEN
		RAISE ERR_PENALTY_TO_DEACTIVATED_USER;
	END IF;
	

	-- 회원 유효성 체크) 영구 정지 처리된 회원이지 확인
	-- 유저의 현재 패널티 총점 확인
    SELECT SUM(PH.PENALTY_SCORE) INTO V_TOTAL_PENALTY_SCORE
    FROM PENALTY_HISTORY PH LEFT OUTER JOIN PENALTY_CANCEL PC
         ON PH.PENALTY_ID = PC.PENALTY_ID
    WHERE PH.USER_ID = P_USER_ID
      AND PENALTY_CANCEL_ID IS NULL;

	-- 영구 정지 점수(4점 이상)면 이미 영구 정지된 회원이므로 예외 발생
	IF V_TOTAL_PENALTY_SCORE >= 4 THEN
		RAISE ERR_PENALTY_TO_BANNED_USER;
	END IF;
	
	
	
	-- 회원 유효성 검사 이후) 패널티 부여 로직 수행
    -- 패널티 이력의 시퀸스 값을 변수로 저장
    -- ㄴ패널티 상태 테이블 INSERT 문에서 재사용하기 위한 목적.
    V_PENALTY_ID := PENALTY_SEQ.NEXTVAL;

    -- 패널티 점수 부여
    INSERT INTO PENALTY_HISTORY (PENALTY_ID, USER_ID, PENALTY_TYPE_ID, ADMIN_ACCOUNT_ID, PENALTY_SCORE, CREATED_AT)
    VALUES (V_PENALTY_ID, P_USER_ID, P_PENALTY_TYPE_ID, P_ADMIN_ACCOUNT_ID, P_PENALTY_SCORE, SYSDATE);
    
    -- 패널티 총점 재계산 (기존의 패널티 점수 + 추가로 부여한 패널티 점수)
    V_TOTAL_PENALTY_SCORE := V_TOTAL_PENALTY_SCORE + P_PENALTY_SCORE;


    -- 패널티 점수가 일정치 이상(1점 초과)이면 제재 발생
    IF V_TOTAL_PENALTY_SCORE > 1 THEN
        CASE
            -- 4점 이상: 영구 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 4
            THEN V_PENALTY_END_DATE := TO_DATE('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

            -- 3점 이상: 30일 정지
            -- 오늘을 기준으로 30일 뒤 23시59분59초까지 계정 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 3
            THEN V_PENALTY_END_DATE := TRUNC(SYSDATE + 30) + (1 - 1/86400);

            -- 그 외(2점 이상): 7일 정지
            -- 오늘을 기준으로 7일 뒤 23시59분59초까지 계정 정지
            ELSE V_PENALTY_END_DATE := TRUNC(SYSDATE + 7) + (1 - 1/86400);
        END CASE;
        
        INSERT INTO PENALTY_STATUS (PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE)
        VALUES (PENALTY_STATUS_SEQ.NEXTVAL, V_PENALTY_ID, SYSDATE, V_PENALTY_END_DATE);
    END IF;



	EXCEPTION
		-- 활동하지 않는 회원(=탈퇴 회원)에게 패널티 부여 시도
		WHEN ERR_PENALTY_TO_DEACTIVATED_USER
		THEN RAISE_APPLICATION_ERROR(-21000, '탈퇴한 회원에게는 패널티 부여가 불가능합니다.');
		
		-- 이미 영구정지된 회원에게 추가 패널티 부여 시도(=의미 없는 패널티 부여)
		WHEN ERR_PENALTY_TO_BANNED_USER
		THEN RAISE_APPLICATION_ERROR(-21001, '이미 영구 정지 처리된 회원에게는 추가 패널티 부여가 불가능합니다.');
		
		WHEN OTHERS
		THEN RAISE; -- 에러 전파 (ROLLBACK 은 프로시저 호출단에서 컨트롤)
END;
/

-- ○ 14. 신고 처리 프로시저
CREATE OR REPLACE PROCEDURE PRC_REPORT_PROCESS
(P_REPORT_SUBMISSION_ID IN REPORT_SUBMISSION.REPORT_SUBMISSION_ID%TYPE
, P_ADMIN_ACCOUNT_ID    IN ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, P_REPORT_RESULT_ID    IN REPORT_RESULT.REPORT_RESULT_ID%TYPE
, P_PROCESSED_REASON    IN REPORT_PROCESS.PROCESS_REASON%TYPE
)
IS
    V_TARGET_ID NUMBER;
    V_PRODUCT_ID PRODUCT.PRODUCT_ID%TYPE;
    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_USER_ID USERS.USER_ID%TYPE;
BEGIN
  
    IF (P_REPORT_RESULT_ID = 1) THEN
    
        SELECT REPORT_TARGET_ID INTO V_TARGET_ID
        FROM REPORT_SUBMISSION
        WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
        
        IF (V_TARGET_ID = 1) THEN
            
            SELECT PRODUCT_ID INTO V_PRODUCT_ID
            FROM PRODUCT_REPORT
            WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
            
            SELECT USER_ID INTO V_USER_ID
            FROM PRODUCT
            WHERE PRODUCT_ID = V_PRODUCT_ID;
            
        ELSIF (V_TARGET_ID = 2) THEN
        
            SELECT AUCTION_ID INTO V_AUCTION_ID
            FROM AUCTION_REPORT
            WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
            
            SELECT PRODUCT_ID INTO V_PRODUCT_ID
            FROM AUCTION_REGISTRATION
            WHERE AUCTION_ID = V_AUCTION_ID;
            
            SELECT USER_ID INTO V_USER_ID
            FROM PRODUCT
            WHERE PRODUCT_ID = V_PRODUCT_ID;
        END IF;
        
        -- 패널티 부여
        IF V_USER_ID IS NOT NULL THEN
            PRC_PENALTY_ASSIGN(V_USER_ID, P_ADMIN_ACCOUNT_ID, 1, 1);
        END IF;
    END IF;
    
    INSERT INTO REPORT_PROCESS(REPORT_PROCESS_ID, REPORT_SUBMISSION_ID, ADMIN_ACCOUNT_ID, REPORT_RESULT_ID, PROCESS_REASON, PROCESSED_AT)
    VALUES(REPORT_PROCESS_SEQ.NEXTVAL, P_REPORT_SUBMISSION_ID, P_ADMIN_ACCOUNT_ID, P_REPORT_RESULT_ID, P_PROCESSED_REASON, SYSDATE);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20030, '해당 신고 내역이나 대상자를 찾을 수 없습니다.');
        WHEN OTHERS THEN
            ROLLBACK;
    
END;
/




-- ○ 16. 패널티 취소 프로시저
CREATE OR REPLACE PROCEDURE PRC_PENALTY_CANCEL
( P_PENALTY_ID              IN          PENALTY_HISTORY.PENALTY_ID%TYPE
, P_ADMIN_ACCOUNT_ID        IN          ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, P_CANCEL_REASON           IN          PENALTY_CANCEL.CANCEL_REASON%TYPE
)
IS
	V_LATEST_PENALTY_CANCEL_YN			CHAR(1);
BEGIN
    -- 패널티 취소 처리
    INSERT INTO PENALTY_CANCEL(PENALTY_CANCEL_ID, PENALTY_ID, ADMIN_ACCOUNT_ID, CANCEL_REASON, CANCELED_AT)
    VALUES(PENALTY_CANCEL_SEQ.NEXTVAL, P_PENALTY_ID, P_ADMIN_ACCOUNT_ID, P_CANCEL_REASON, SYSDATE);


	-- 가장 마지막(가장 최신의) 패널티가 취소된 것인지 확인
	SELECT
		CASE WHEN PENALTY_ID = P_PENALTY_ID
			 THEN 'Y'
			 
			 ELSE 'N'
		END INTO V_LATEST_PENALTY_CANCEL_YN
	FROM (
			SELECT PH.*
				 , ROW_NUMBER() OVER(ORDER BY PENALTY_ID DESC) AS PENALTY_NUM
			FROM PENALTY_HISTORY PH
			WHERE USER_ID = (
								SELECT USER_ID
								FROM PENALTY_HISTORY
								WHERE PENALTY_ID = P_PENALTY_ID
							)
		 )
	WHERE PENALTY_NUM = 1;


    -- 가장 최근의 패널티 취소인지 여부에 맞춰 계정의 패널티 상태(=정지 제재) 업데이트
	-- 가장 최근의 패널티가 취소되었을 경우...
	IF V_LATEST_PENALTY_CANCEL_YN = 'Y' THEN
		-- 이 패널티로 발생했던 패널티 상태(=정지 제재) 해제 처리
	    --  ㄴ 해당 패널티에 연관된 패널티 상태 레코드 삭제
	    --  ㄴ (별도의 상태 분류가 가능한 컬럼이나 테이블이 없어 삭제로 처리)
	    DELETE
	    FROM PENALTY_STATUS
	    WHERE PENALTY_ID = P_PENALTY_ID;
    
    -- 가장 최근의 패널티가 아닌, 그 이전의 패널티가 취소되었을 경우...
   -- ELSE
    	-- 현재의 총점에 맞춰 패널티 상태 업데이트 처리

    	-- (로직 작성 영역...)
	END IF;

END;
/

-- 낙찰 실패 처리 프로시저(낙찰 취소 처리 프로시저, 실패는 스케줄러로만)
CREATE OR REPLACE PROCEDURE PRC_BID_FAILURE_PROCESS
(
   V_USER_ID USERS.USER_ID%TYPE
   ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
   
)
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_PENALTY_TYPE_ID PENALTY_ASSIGN_TYPE.PENALTY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    V_TOTAL_PENALTY_SCORE       PENALTY_HISTORY.PENALTY_SCORE%TYPE;
    V_PENALTY_END_DATE          PENALTY_STATUS.PENALTY_END_DATE%TYPE;
    N_PENALTY_ID                PENALTY_HISTORY.PENALTY_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '낙찰포기';

    -- 낙찰 실패 이력
    INSERT INTO BID_FAILURE_HISTORY(BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    VALUES(BID_FAIL_HISTORY_SEQ.NEXTVAL,V_RESULT_ID,N_BID_FAIL_TYPE_ID);

    SELECT NVL(PENALTY_TYPE_ID,0) INTO N_PENALTY_TYPE_ID
    FROM PENALTY_ASSIGN_TYPE
    WHERE PENALTY_TYPE_NAME = '자동';

    N_PENALTY_ID := PENALTY_SEQ.NEXTVAL;
    
    -- 구매자 패널티 부여
    INSERT INTO PENALTY_HISTORY(PENALTY_ID,USER_ID,PENALTY_TYPE_ID,ADMIN_ACCOUNT_ID,PENALTY_SCORE)
    VALUES(N_PENALTY_ID,V_USER_ID,N_PENALTY_TYPE_ID,NULL,1);
    
    SELECT SUM(PH.PENALTY_SCORE) INTO V_TOTAL_PENALTY_SCORE
    FROM PENALTY_HISTORY PH LEFT OUTER JOIN PENALTY_CANCEL PC
         ON PH.PENALTY_ID = PC.PENALTY_ID
    WHERE PH.USER_ID = V_USER_ID
      AND PENALTY_CANCEL_ID IS NULL;
   
    -- 패널티 점수가 일정치 이상(1점 초과)이면 제재 발생
    IF V_TOTAL_PENALTY_SCORE > 1 THEN
        CASE
            -- 4점 이상: 영구 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 4
            THEN V_PENALTY_END_DATE := TO_DATE('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

            -- 3점 이상: 30일 정지
            -- 오늘을 기준으로 30일 뒤 23시59분59초까지 계정 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 3
            THEN V_PENALTY_END_DATE := TRUNC(SYSDATE + 30) + (1 - 1/86400);

            -- 그 외(2점 이상): 7일 정지
            -- 오늘을 기준으로 7일 뒤 23시59분59초까지 계정 정지
            ELSE V_PENALTY_END_DATE := TRUNC(SYSDATE + 7) + (1 - 1/86400);
        END CASE;

        INSERT INTO PENALTY_STATUS (PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE)
        VALUES (PENALTY_STATUS_SEQ.NEXTVAL, N_PENALTY_ID, SYSDATE, V_PENALTY_END_DATE);
    END IF;



    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A INNER JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID AND B.USER_ID = V_USER_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;

    -- 구매자 보증금 몰수
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID,N_MONEY_TYPE_ID1,N_AUCTION_ID,0);

    -- 이외 구매자 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE_ID3,N_AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    AND USER_ID != V_USER_ID;

    -- 판매자 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE_ID4,N_AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID;

    COMMIT;

    EXCEPTION 
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;
/





-- 함수 =========================================================================



-- ○ 1. 회원 잔여 머니 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(P_USER_ID IN USERS.USER_ID%TYPE
)
RETURN NUMBER
IS
    V_MONEY1    NUMBER;
    V_MONEY2    NUMBER;
BEGIN

-- 머니입출금이력테이블에서 아이디로 조회해서 금액 계산한 값 +
-- 머니 충전 이력 테이블에서 아이디로 조회해서 금액 계산한 값

    SELECT NVL(SUM(AMOUNT), 0) INTO V_MONEY1
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO V_MONEY2
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    RETURN V_MONEY1+V_MONEY2;
    
    EXCEPTION 
        WHEN OTHERS THEN
            RETURN -1;
END;
/

-- ○ 2. 경매 현재가 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_AUCTION_CURRENT_PRICE
(
    P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_CURRENT_PRICE NUMBER;
    V_START_PRICE   NUMBER;
    V_BID_COUNT     NUMBER;
BEGIN

    -- 경매 시작가 조회
    SELECT START_PRICE INTO V_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 입찰자 수 확인
    SELECT COUNT(*) INTO V_BID_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 0명 또는 1명이면 시작가 반환
    IF V_BID_COUNT <= 1 THEN
        RETURN V_START_PRICE;
    END IF;

    -- 2명 이상부터  →2등 금액 가져오기
    SELECT BID_PRICE INTO V_CURRENT_PRICE
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID
    ORDER BY BID_PRICE DESC
    OFFSET 1 ROW FETCH NEXT 1 ROW ONLY;

    RETURN V_CURRENT_PRICE;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE;
END;
/

-- ○ 3. 경매 입찰 단위 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_BID_UNIT
(
    P_START_PRICE IN NUMBER  -- 경매 시작가
)
RETURN NUMBER
IS
    V_BID_UNIT NUMBER;
BEGIN
      
    IF P_START_PRICE < 1000000 THEN
        -- 100만원 미만
        V_BID_UNIT := 1000;
        
    ELSIF P_START_PRICE < 10000000 THEN
        -- 100만원 이상 ~ 1,000만원 미만
        V_BID_UNIT := 10000;
        
    ELSE
        -- 1,000만원 이상
        V_BID_UNIT := 100000;
        
    END IF;

    RETURN V_BID_UNIT;
END;
/

-- ○ 4. 경매 입찰 상한가 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_BID_MAX_LIMIT
(
    P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_CURRENT_PRICE NUMBER;
BEGIN
    -- 현재가 조회 (2순위 금액)
    V_CURRENT_PRICE := FN_GET_AUCTION_CURRENT_PRICE(P_AUCTION_ID);

    -- 현재가의 2배
    RETURN V_CURRENT_PRICE * 2;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE;
END;
/

-- ○ 5. 경매 최초 입찰 여부 확인 함수
CREATE OR REPLACE FUNCTION FN_IS_FIRST_BIDDER
(
    P_AUCTION_ID IN NUMBER
)
RETURN CHAR 
IS
    V_COUNT NUMBER;
    V_RESULT CHAR(1);
BEGIN
    -- 입찰 참여 테이블에서 해당 경매의 입찰 기록 개수를 카운트
    SELECT COUNT(*) INTO V_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 0이면 최초 입찰(Y), 0보다 크면 입찰 기록 있음(N)
    IF V_COUNT = 0 THEN
        V_RESULT := 'Y';
    ELSE
        V_RESULT := 'N';
    END IF;

    RETURN V_RESULT;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'N'; -- 에러 발생 시 입찰취소로 예외 처리
END;
/

-- ○ 6. 회원 진행중 입찰 건수 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_ACTIVE_BID_COUNT
(
    P_USER_ID IN NUMBER
)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    -- 1. 내가 입찰한 모든 기록 중에서
    -- 2. 그 경매가 '진행 중(0)'인 것만 개수를 셉니다.
    SELECT COUNT(*) INTO V_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE USER_ID = P_USER_ID
    AND FN_IS_AUCTION_FINISHED(AUCTION_ID) = 0; -- 0이면 경매 진행중

    RETURN V_COUNT;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/

-- ○ 7. 회원 패널티 누적 점수 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_PENALTY_SCORE (
    P_USER_ID NUMBER
) 
RETURN NUMBER
IS
    -- 총 점수 0으로 초기화
    V_TOTAL_SCORE       NUMBER := 0;            -- 총 패널티 누적 점수
    ERR_UNKNOWN         CONSTANT NUMBER := -20009;
    
BEGIN

    -- 전체 누적 점수에서 취소된 점수를 뺀 값을 계산
    SELECT (
        (SELECT NVL(SUM(PENALTY_SCORE), 0) 
         FROM PENALTY_HISTORY 
         WHERE USER_ID = P_USER_ID) 
        - 
        (SELECT NVL(SUM(PH.PENALTY_SCORE), 0) 
         FROM PENALTY_CANCEL PC 
         JOIN PENALTY_HISTORY PH ON PC.PENALTY_ID = PH.PENALTY_ID 
         WHERE PH.USER_ID = P_USER_ID)
    ) INTO V_TOTAL_SCORE
    FROM DUAL;

    -- 패널티 누적 점수 반환
    RETURN V_TOTAL_SCORE;
EXCEPTION
     WHEN OTHERS THEN
        RETURN 0;
        
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF; 
END;
/

-- ○ 8. 회원 패널티 활성 상태 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_PENALTY_STATUS (
    P_USER_ID NUMBER
)
RETURN NUMBER
IS
    V_STATUS    NUMBER;        -- 0이면 활성, 1이면 비활성
    ERR_UNKNOWN  CONSTANT NUMBER := -20009;

BEGIN
    IF FN_GET_USER_PENALTY_SCORE(P_USER_ID) > 0
    THEN V_STATUS := 0;
    ELSE
        V_STATUS := 1;
    END IF;
    
    RETURN V_STATUS;
EXCEPTION

     WHEN OTHERS THEN     
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF; 
END;
/


-- ○ 9. 낙찰 입찰코드 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_WINNING_BID_ID
( P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_WINNIG_ID NUMBER;
BEGIN
    SELECT BID_ID INTO V_WINNIG_ID
    FROM VW_BID_LIST
    WHERE AUCTION_ID = P_AUCTION_ID AND BID_RANK = 1;
    
    RETURN V_WINNIG_ID;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1;
        WHEN OTHERS THEN
            RETURN -1;
END;
/


-- ○ 10. 경매 마감여부 확인 함수
CREATE OR REPLACE FUNCTION FN_IS_AUCTION_FINISHED
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN NUMBER
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
    V_RESULT NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    IF (SYSDATE < (V_START_DATE+V_AUCTION_PERIOD)) THEN
        RETURN 0;   -- 경매 중
    ELSE
        RETURN 1;   -- 경매 종료
    END IF;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; --(경매 정보가 없는 경우에 대한 예외 처리)
        WHEN OTHERS THEN
            RETURN -1;
END;
/

-- ○ 11. 경매 마감일자  확인 함수
CREATE OR REPLACE FUNCTION FN_GET_AUCTION_DUE_DATE
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN VARCHAR2
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    
    RETURN TO_CHAR(V_START_DATE+V_AUCTION_PERIOD, 'YYYY-MM-DD HH24:MI');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '-'; 
        WHEN OTHERS THEN
            RETURN '-';
END;
/


-- 스케줄러 ======================================================================

-- ○ 1. 경매 종료 처리 스케줄러
-- 경매 종료 처리 스케줄러

-- 스케쥴러에 사용할 프로시저 생성
-- 경매 모니터링 및 마감 처리 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUCTION_MONITORING
IS
	CURSOR CUR_CLOSED_AUCTION
	IS
	SELECT AUCTION_ID
	FROM VW_AUCTION_WINNING_RESULT		-- 뷰 사용
	WHERE AUCTION_STATUS = 'Closed';

	V_RESULT		VARCHAR2(300);		-- 프로시저의 OUT 변수 바인딩용 변수 (스케쥴러에서 실제 사용하진 않음)
BEGIN

	FOR V_AUCTION_REC IN CUR_CLOSED_AUCTION LOOP
		PRC_AUCTION_CLOSE(P_AUCTION_ID => V_AUCTION_REC.AUCTION_ID, P_RESULT => V_RESULT);
	END LOOP;
	
END;
/

-- 1. 프로그램 정의
BEGIN
    DBMS_SCHEDULER.CREATE_PROGRAM (
        program_name     => 'PROG_AUCTION_MONITORING'
        , program_type   => 'STORED_PROCEDURE'
        , program_action => 'PRC_AUCTION_MONITORING'
        , enabled        => TRUE
        , comments       => '마감 경매 낙찰 처리'
    );
END;

-- 2. 일정 정의
BEGIN
    DBMS_SCHEDULER.CREATE_SCHEDULE (
        schedule_name     => 'SCH_AUCTION_MONITORING_EVERY_MINUTE'
        , start_date      => SYSTIMESTAMP						-- 현재 시점에서 바로 시작
        , repeat_interval => 'FREQ=MINUTELY; INTERVAL=1'		-- 1분마다 작업
        , comments        => '매 분마다 경매 모니터링'
    );
END;

-- 3. Job 생성 및 연결
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name          => 'SCH_AUCTION_MONITORING'
        , program_name    => 'PROG_AUCTION_MONITORING'
        , schedule_name   => 'SCH_AUCTION_MONITORING_EVERY_MINUTE'
        , enabled         => TRUE			-- 생성 즉시 활성화
        , auto_drop       => FALSE			-- 작업 완료 후에도 삭제되지 않음
        , comments        => '매 분마다 경매 모니터링 및 마감 경매 낙찰 처리'
    );
END;



-- ○ 2. 낙찰 결제 기한 확인 스케줄러
-- 낙찰 결제 기한 확인 스케줄러(컴파일O,테스트X)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
    JOB_NAME => 'SCH_AUCTION_CLOSE'
    ,JOB_TYPE => 'STORED_PROCEDURE'
    ,JOB_ACTION => 'REC_AUCTION_CLOSE'
    ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
    ,ENABLED => FALSE
    );
END;


--  낙찰 결제 기한 확인 스케줄러용 프로시저
-- 낙찰 결제 기한 확인 스케줄러(프로시저) -- 실행 불가
CREATE OR REPLACE PROCEDURE REC_AUCTION_CLOSE
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_PENALTY_TYPE_ID PENALTY_ASSIGN_TYPE.PENALTY_TYPE_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '결제기한만료';
    
    IF(N_BID_FAIL_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "결제기한만료" 코드명이 존재하지 않습니다');
    END IF;

    -- 낙찰 실패 이력
    INSERT INTO (BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    SELECT BID_FAIL_HISTORY_SEQ.NEXTVAL,M.BID_RESULT_ID,N_BID_FAIL_TYPE_ID
    FROM
        (
            SELECT A.BID_RESULT_ID
            ,CASE 
             WHEN A.CREATED_AT IS NULL THEN '오류'
             WHEN A.CREATED_AT+1 >= SYSDATE THEN '안전'
             WHEN A.CREATED_AT+1 < SYSDATE THEN '마감'
             ELSE '오류'
             END AS CREATED_AT
            FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_WINNING_PAYMENT B
            ON A.BID_RESULT_ID = B.BID_RESULT_ID
            LEFT JOIN BID_FAILURE_HISTORY C
            ON A.BID_RESULT_ID = C.BID_RESULT_ID
            WHERE B.BID_RESULT_ID IS NULL AND C.BID_RESULT_ID IS NULL
        )M
    WHERE M.CREATED_AT = '마감';


    SELECT NVL(PENALTY_TYPE_ID,0) INTO N_PENALTY_TYPE_ID
    FROM PENALTY_ASSIGN_TYPE
    WHERE PENALTY_TYPE_NAME = '자동';

    IF(N_PENALTY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20111,'패널티 분류 코드명에 "자동"인 코드명이 존재하지 않습니다');
    END IF;


    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    
    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;
    
    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;
    

    -- 패널티 입력(대기)
    INSERT INTO PENALTY_HISTORY(PENALTY_ID,USER_ID,PENALTY_TYPE_ID,ADMIN_ACCOUNT_ID,PENALTY_SCORE)
    SELECT PENALTY_SEQ.NEXTVAL,C.USER_ID,N_PENALTY_TYPE_ID,NULL,1
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     LEFT JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE D.MONEY_ID IS NULL;

    -- 구매자 보증금 환급 이력(수정 : 환급 -> 몰수)
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
     SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,C.USER_ID,N_MONEY_TYPE_ID,C.AUCTION_ID,0
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     INNER JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
     LEFT JOIN MONEY_TRANSACTION_HISTORY E
     ON C.AUCTION_ID = E.AUCTION_ID AND C.USER_ID = E.USER_ID
     AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE E.MONEY_ID IS NULL;

     -- 실구매자 이외 구매자 환급 이력(대기)
    -- INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    -- ,AUCTION_ID,AMOUNT)
    -- SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,A.USER_ID,N_MONEY_TYPE_ID2,A.AUCTION_ID,D.AMOUNT
    --  FROM AUCTION_BID_PARTICIPATION A LEFT JOIN AUCTION_WINNING_RESULT B
    --  ON A.BID_ID = B.BID_ID
    --  LEFT JOIN BID_FAILURE_HISTORY C
    --  ON B.BID_RESULT_ID = C.BID_RESULT_ID
    --  LEFT JOIN MONEY_TRANSACTION_HISTORY D
    --  ON A.USER_ID = D.USER_ID AND A.AUCTION_ID = D.AUCTION_ID
    --  AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
    --  LEFT JOIN MONEY_TRANSACTION_HISTORY E
    --  ON A.USER_ID = E.USER_ID AND A.AUCTION_ID = E.AUCTION_ID
    --  AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    --  WHERE B.BID_ID IS NULL
    --  AND E.MONEY_TYPE_ID IS NULL
    --  AND C;

     -- 실구매자 이외 구매자 환급 이력
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT)
    SELECT 
    MONEY_TRANSACTION_SEQ.NEXTVAL
    ,A.USER_ID
    ,N_MONEY_TYPE_ID2       -- 구매 보증금 환급
    ,A.AUCTION_ID
    ,D.AMOUNT
    FROM AUCTION_BID_PARTICIPATION A
-- 보증금 납부 이력 (환급 금액 가져오기)
    INNER JOIN MONEY_TRANSACTION_HISTORY D
    ON A.USER_ID = D.USER_ID 
    AND A.AUCTION_ID = D.AUCTION_ID
    AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1  -- 구매 보증금 납부
-- 아직 환급 안 된 사람만
    LEFT JOIN MONEY_TRANSACTION_HISTORY E
    ON A.USER_ID = E.USER_ID 
    AND A.AUCTION_ID = E.AUCTION_ID
    AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID2  -- 구매 보증금 환급
-- 낙찰 실패가 발생한 경매인지 확인
    WHERE A.AUCTION_ID IN (
    SELECT BP.AUCTION_ID
    FROM AUCTION_BID_PARTICIPATION BP
    INNER JOIN AUCTION_WINNING_RESULT WR ON BP.BID_ID = WR.BID_ID
    INNER JOIN BID_FAILURE_HISTORY FH ON WR.BID_RESULT_ID = FH.BID_RESULT_ID
    )
    -- 실구매자(낙찰자) 제외
    AND A.BID_ID NOT IN (
    SELECT WR2.BID_ID
    FROM AUCTION_WINNING_RESULT WR2
    INNER JOIN BID_FAILURE_HISTORY FH2 ON WR2.BID_RESULT_ID = FH2.BID_RESULT_ID
    )
    AND E.MONEY_ID IS NULL;
    
    
    -- 판매자 보증금 몰수(수정: 몰수 -> 환급)
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,E.USER_ID,N_MONEY_TYPE_ID4,C.AUCTION_ID,F.AMOUNT
    FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
    ON A.BID_RESULT_ID = B.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION C
    ON B.BID_ID = C.BID_ID
    INNER JOIN AUCTION_REGISTRATION D
    ON C.AUCTION_ID = D.AUCTION_ID
    INNER JOIN PRODUCT E
    ON D.PRODUCT_ID = E.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY F
    ON E.USER_ID = F.USER_ID AND F.AUCTION_ID = D.AUCTION_ID
    AND F.MONEY_TYPE_ID = N_MONEY_TYPE_ID3
    LEFT JOIN MONEY_TRANSACTION_HISTORY G
    ON E.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID4
    WHERE G.MONEY_ID IS NULL;
    
    COMMIT;
    
    EXCEPTION
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
    
END;


-- ○ 3. 구매 확정 자동 처리 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_AUTO_PURCHASE_CONFIRM'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_AUTO_PURCHASE_CONFIRM'
        ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
        ,ENABLED => FALSE
    );
END;
/가

-- 구매 확정 자동 처리 스케줄러용 프로시저
-- 구매 확정 자동 처리 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_AUTO_PURCHASE_CONFIRM
IS
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID5 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID6 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
BEGIN

    -- 구매 확정 이력
    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    SELECT PURCHASE_CONFIRM_SEQ.NEXTVAL,M.SHIPPING_ID
    FROM
        (
            SELECT A.SHIPPING_ID
            FROM DELIVERY_COMPLETED A LEFT JOIN PURCHASE_CONFIRM_HISTORY B
            ON A.SHIPPING_ID = B.SHIPPING_ID
            WHERE B.SHIPPING_ID IS NULL
            AND A.CREATED_AT+3 < SYSDATE
        )M;

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID5
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID6
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금';
    
    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID5 = 0)
        THEN RAISE_APPLICATION_ERROR(-20112,'머니 분류 테이블에 "결제" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID6 = 0)
        THEN RAISE_APPLICATION_ERROR(-20113,'머니 분류 테이블에 "결제 대금" 코드명이 존재하지 않습니다');
    END IF;

    -- 구매 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,F.USER_ID,N_MONEY_TYPE_ID1,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON F.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
    WHERE H.MONEY_ID IS NULL;
    -- GROUP BY F.USER_ID
    
    -- 판매보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,J.USER_ID,N_MONEY_TYPE_ID3,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN AUCTION_REGISTRATION I
    ON F.AUCTION_ID = I.AUCTION_ID
    INNER JOIN PRODUCT J
    ON I.PRODUCT_ID = J.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON J.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID4
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID3
    WHERE H.MONEY_ID IS NULL;
    
    -- 구매대금 판매자에게 이력추가
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,J.USER_ID,N_MONEY_TYPE_ID6,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN AUCTION_REGISTRATION I
    ON F.AUCTION_ID = I.AUCTION_ID
    INNER JOIN PRODUCT J
    ON I.PRODUCT_ID = J.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON F.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID5
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID6
    WHERE H.MONEY_ID IS NULL;
    
    -- 구매 확정 이력
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    SELECT TRANSACTION_SEQ.NEXTVAL,A.PURCHASE_CONFIRM_ID
    FROM PURCHASE_CONFIRM_HISTORY A LEFT JOIN TRANSACTION_COMPLETED B
    ON A.PURCHASE_CONFIRM_ID = B.PURCHASE_CONFIRM_ID
    WHERE B.TRANSACTION_ID IS NULL;

    COMMIT;

    EXCEPTION
    WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;
/

-- ○ 4. 탈퇴 회원 정리 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_DELETED_USER_CLEANUP'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_DELETED_USER_CLEANUP' 
        ,REPEAT_INTERVAL => 'FREQ=DAILY; BYHOUR=0'
        ,ENABLED => FALSE
    );
END;


-- 탈퇴 회원 정리 스케줄러용 프로시저
-- 탈퇴 회원 정리 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_DELETED_USER_CLEANUP
IS
    N_ACCOUNT_EVENT_TYPE_ID ACCOUNT_EVENT_TYPE.ACCOUNT_EVENT_TYPE_ID%TYPE;
BEGIN
    SELECT NVL(ACCOUNT_EVENT_TYPE_ID,0) INTO N_ACCOUNT_EVENT_TYPE_ID
    FROM ACCOUNT_EVENT_TYPE
    WHERE EVENT_NAME = '탈퇴';

    IF(N_ACCOUNT_EVENT_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이없습니다');
    END IF;
    
    DELETE 
    FROM DELETED_USER A
    WHERE EXISTS
    (SELECT 1
    FROM ACCOUNT_EVENT_HISTORY B
    WHERE A.USER_ID = B.USER_ID
    AND B.ACCOUNT_EVENT_TYPE_ID = N_ACCOUNT_EVENT_TYPE_ID
    AND ADD_MONTHS(B.CREATED_AT,3) < SYSDATE  
    );
    
    COMMIT;
    EXCEPTION
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;
/

