
-- 뷰 ===========================================================================

-- ○ 1. 회원 통합 정보 조회 뷰
CREATE OR REPLACE VIEW VW_USER_INFO
AS
SELECT U.USER_ID, UA.USER_LOGIN_ID, UA.USER_PASSWORD
, UP.USER_NAME, UP.USER_SSN, UP.USER_EMAIL, UP.USER_PHONE
, UP.USER_ZIPCODE, UP.USER_ADDRESS, UP.USER_ADDRESS_DETAIL
, FN_GET_USER_MONEY_BALANCE(U.USER_ID) AS TOTAL_MONEY
, CASE WHEN (AEH.ACCOUNT_EVENT_TYPE_ID = 1) THEN
        AEH.CREATED_AT
        END AS CREATED_AT
, CASE WHEN (AEH.ACCOUNT_EVENT_TYPE_ID = 2) THEN
        AEH.CREATED_AT
        ELSE NULL
        END AS DELETED_AT
FROM USERS U JOIN USER_ACCOUNT UA
ON U.USER_ID = UA.USER_ID
JOIN USER_PROFILE UP
ON UA.USER_ID = UP.USER_ID
JOIN ACCOUNT_EVENT_HISTORY AEH ON UP.USER_ID = AEH.USER_ID
;


-- ○ 2. 상품 통합 조회 뷰
CREATE OR REPLACE VIEW VW_PRODUCT_LIST
AS
SELECT 
    P.PRODUCT_ID, P.USER_ID, P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME
    , P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME, P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME
    , P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME, P.PURCHASE_DATETIME
    ,CASE WHEN P.IS_OPENED = 0 THEN '개봉' ELSE '미개봉' END AS IS_OPENED
    ,CASE WHEN P.IS_PARTS_MISSING = 0 THEN '정상' ELSE '누락' END AS IS_PARTS_MISSING
    ,P.DESCRIPTIONS
    ,P.IMAGE_PATH_1
    ,P.IMAGE_PATH_2
    ,P.IMAGE_PATH_3
    ,MAX(DECODE(PI.IMAGE_ORDER, 1, PI.FILE_PATH)) AS IMAGE_PATH_4
    ,MAX(DECODE(PI.IMAGE_ORDER, 2, PI.FILE_PATH)) AS IMAGE_PATH_5
    ,MAX(DECODE(PI.IMAGE_ORDER, 3, PI.FILE_PATH)) AS IMAGE_PATH_6
    ,MAX(DECODE(PI.IMAGE_ORDER, 4, PI.FILE_PATH)) AS IMAGE_PATH_7
    ,MAX(DECODE(PI.IMAGE_ORDER, 5, PI.FILE_PATH)) AS IMAGE_PATH_8
    ,MAX(DECODE(PI.IMAGE_ORDER, 6, PI.FILE_PATH)) AS IMAGE_PATH_9
    ,MAX(DECODE(PI.IMAGE_ORDER, 7, PI.FILE_PATH)) AS IMAGE_PATH_10
    ,CASE WHEN P.IS_PUBLIC = 0 THEN '비공개' ELSE '공개' END AS IS_PUBLIC
    ,TO_CHAR(P.CREATED_AT, 'YYYY-MM-DD') AS CREATED_AT
FROM PRODUCT P
    JOIN PRODUCT_MANUFACTURER PM ON P.MANUFACTURER_ID = PM.MANUFACTURER_ID
    JOIN PRODUCT_COUNTRY PC      ON PM.PRODUCT_COUNTRY_ID = PC.PRODUCT_COUNTRY_ID
    JOIN PRODUCT_GRADE PG        ON P.PRODUCT_GRADE_ID = PG.PRODUCT_GRADE_ID
    JOIN PRODUCT_GENRE PGR       ON P.PRODUCT_GENRE_ID = PGR.PRODUCT_GENRE_ID
    JOIN PRODUCT_SIZE PS         ON P.PRODUCT_SIZE_ID = PS.PRODUCT_SIZE_ID
    LEFT JOIN PRODUCT_IMAGE PI   ON P.PRODUCT_ID = PI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, P.USER_ID,
    P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME, 
    P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME,
    P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, 
    P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME, 
    P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME,
    P.PURCHASE_DATETIME, P.IS_OPENED, P.IS_PARTS_MISSING, P.DESCRIPTIONS,
    P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3, P.IS_PUBLIC, P.CREATED_AT;


-- ○ 3. 경매 통합 조회 뷰
CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, VPI.USER_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_DATE(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    TO_DATE(FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID),'YYYY-MM-DD HH24:MI') AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중'
         ELSE '마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID;


-- ○ 4. 입찰 통합 조회 뷰
CREATE OR REPLACE VIEW VW_BID_LIST
AS
WITH BID_RANKING AS (
    -- 모든 입찰 기록에 대해 실시간 순위를 매김
    SELECT 
        BID_ID, AUCTION_ID, USER_ID, BID_PRICE, BID_TIME,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    BR.BID_ID, BR.BID_PRICE,
    TO_CHAR(BR.BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    BR.RK AS BID_RANK,
    CASE WHEN BR.RK = 1 THEN '낙찰유력' 
         WHEN BR.RK >4 THEN '순위권'
        ELSE '입찰중' END AS BID_STATUS,
    BR.USER_ID AS BIDDER_ID, UP.USER_ID , UA.USER_LOGIN_ID,
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.START_PRICE,
    TO_DATE(FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID),'YYYY-MM-DD HH24:MI') AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중' ELSE '마감' END AS AUCTION_STATUS,
    VPL.PRODUCT_ID, VPL.PRODUCT_RELEASE_NAME, VPL.MANUFACTURER_NAME,
    NVL(
        (SELECT BID_PRICE FROM BID_RANKING WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2),
        AR.START_PRICE
    ) AS CURRENT_PRICE
FROM BID_RANKING BR
JOIN AUCTION_REGISTRATION AR ON BR.AUCTION_ID = AR.AUCTION_ID
JOIN USER_PROFILE UP ON BR.USER_ID = UP.USER_ID
JOIN USER_ACCOUNT UA ON UP.USER_ID = UA.USER_ID
JOIN VW_PRODUCT_LIST VPL ON AR.PRODUCT_ID = VPL.PRODUCT_ID;


-- ○ 5. 경매 낙찰 결제 통합 조회 뷰
CREATE OR REPLACE VIEW VW_AUCTION_WINNING_RESULT
AS
SELECT
	  ---------- 경매 기본 정보 SELECT ----------
		AR_INFO.AUCTION_ID AS AUCTION_ID
	  , AR_INFO.PRODUCT_ID AS PRODUCT_ID
	  , AR_INFO.AUCTION_TITLE AS AUCTION_TITLE
	  , AR_INFO.AUCTION_CONTENT AS AUCTION_CONTENT
	  , AR_INFO.START_PRICE AS START_PRICE
	  , AR_INFO.CREATED_AT AS CREATED_AT
	  , AR_INFO.AUCTION_PERIOD_ID AS AUCTION_PERIOD_ID
	  
	  ---------- 경매 낙찰 정보 SELECT ----------
	  , AR_WINNING_INFO.USER_ID AS WINNING_USER_ID
	  , AR_WINNING_INFO.BID_ID AS WINNING_BID_ID
	  , AR_WINNING_INFO.BID_TIME AS WINNING_BID_TIME
	  , AR_WINNING_INFO.BID_PRICE AS WINNING_BID_PRICE
	  
	  -- 현재가 처리 (2건 이상 입찰: 2번째 입찰가 출력 | 1건 입찰 : 경매 시작가)
	  --  ㄴ 사전에 계산한 경매 현재가(낙찰가)의 계산 공식에서
	  --     2번째 값이 없을 경우(입찰이 1건일 경우) NULL 이 나오므로
	  --     그에 대한 추가 처리 진행.
	  , CASE WHEN AR_WINNING_INFO.SECOND_BID_PRICE IS NULL
			 THEN AR_INFO.START_PRICE
			 
			 ELSE AR_WINNING_INFO.SECOND_BID_PRICE
		END AS AUCTION_FINAL_PRICE
		
	  -- 경매 진행 여부 (현재 시간과 경매 종료 일시를 비교)
	  , CASE WHEN AR_INFO.AUCTION_END_DATE > SYSDATE
			 THEN 'Active' -- 경매 진행중
			 
			 ELSE 'Closed' -- 경매 종료
	    END AS AUCTION_STATUS

	  ---------- 낙찰 정보 SELECT ----------
	  , CASE WHEN AR_INFO.AUCTION_END_DATE > SYSDATE
			 THEN 'In Progress' -- 낙찰자 미확정(경매 진행중)

			 WHEN AR_INFO.AUCTION_END_DATE <= SYSDATE AND AWR.BID_RESULT_ID IS NOT NULL
				  -- 경매 종료 AND 낙찰자 확정
			 THEN 'Sold' -- 낙찰 완료

			 ELSE 'No Winner' -- 낙찰자 없음
		END WINNING_STATUS
	  
	  ---------- 낙찰 후 대금 지불 정보 SELECT ----------
	  , CASE WHEN AWP.PAYMENT_ID IS NOT NULL 
			THEN 'Completed'	-- 대금 지불 완료
	  	   
			ELSE 'Pending'		-- 대금 지불 대기중
		END AS WINNING_PAYMENT_STATUS
	  , AWP.MONEY_ID AS WINNING_PAYMENT_MONEY_ID	-- 결제에 대한 MONEY ID
	  , AWP.CREATED_AT AS WINNING_PAYMENT_DATE		-- 결제일
	  
	  ---------- 낙찰 취소 정보 SELECT ----------
	  , CASE WHEN BFH.BID_FAIL_HISTORY_ID IS NOT NULL
			 THEN 'Y'	-- 낙찰 취소
			 
			 ELSE 'N'	-- 낙찰 취소되지 않음 (낙찰 절차 진행중)
		END AS BID_FAIL_YN
	  , BFH.BID_FAIL_TYPE_ID AS BID_FAIL_TYPE
	  	-- 1	결제기한만료
	  	-- 2	낙찰포기
	  
	  ---------- 배송 정보 SELECT ----------
	  , CASE WHEN DC.SHIPPING_ID IS NOT NULL
			 THEN 'Y'
			 
			 ELSE 'N'
	    END AS SHIPPING_YN
	  , DC.CREATED_AT AS SHIPPING_DATE
	  
	  ---------- 구매 확정 정보 SELECT ----------
	  , CASE WHEN PCH.PURCHASE_CONFIRM_ID IS NOT NULL
			 THEN 'Y'
			 
			 ELSE 'N'
	    END AS PURCHASE_CONFIRM_YN
	  , PCH.CREATED_AT AS PURCHASE_CONFIRM_DATE
FROM
	-- 경매 정보 테이블 (경매 종료 시간 포함)
	(
		SELECT AR.*
			 , CASE
				 	-- 경매 기간 1일~7일
				 	WHEN AUCTION_PERIOD_ID >= 1 AND AUCTION_PERIOD_ID <= 7
				 	THEN CREATED_AT + AUCTION_PERIOD_ID
				 	
				 	-- 8번 이상 코드 생길 경우, 이 아래에 추가 작성...
				END AS AUCTION_END_DATE
		FROM AUCTION_REGISTRATION AR
	) AR_INFO
	
	-- (입찰 기록을 기반으로) 각 경매의 <최고 입찰>의 '입찰코드' 및 '경매의 현재가(낙찰가)'
	JOIN
	(
		SELECT *
		FROM (
				SELECT ABP.*
					 , ROW_NUMBER() OVER(PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS BID_RANK
					 , LEAD(BID_PRICE) OVER(PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS SECOND_BID_PRICE
				FROM AUCTION_BID_PARTICIPATION ABP
			 )
		WHERE BID_RANK = 1
	) AR_WINNING_INFO
	ON AR_INFO.AUCTION_ID = AR_WINNING_INFO.AUCTION_ID

	-- 낙찰 결과 테이블 OUTER JOIN
	LEFT OUTER JOIN AUCTION_WINNING_RESULT AWR
	ON AR_WINNING_INFO.BID_ID = AWR.BID_ID
	
	-- 낙찰 입금 테이블 OUTER JOIN
	LEFT OUTER JOIN AUCTION_WINNING_PAYMENT AWP
	ON AWR.BID_RESULT_ID = AWP.BID_RESULT_ID
	
	-- 낙찰 실패 이력 테이블 OUTER JOIN
	LEFT OUTER JOIN BID_FAILURE_HISTORY BFH
	ON AWR.BID_RESULT_ID = BFH.BID_RESULT_ID
	
	-- 배송 정보(발송 완료) 테이블 OUTER JOIN
	LEFT OUTER JOIN DELIVERY_COMPLETED DC
	ON AWP.PAYMENT_ID = DC.PAYMENT_ID
	
	-- 구매 확정 이력 테이블 OUTER JOIN
	LEFT OUTER JOIN PURCHASE_CONFIRM_HISTORY PCH
	ON DC.SHIPPING_ID = PCH.SHIPPING_ID
;


-- ○ 6. 패널티 통합 조회 뷰
CREATE OR REPLACE VIEW VW_PENALTY_LIST
AS
WITH RAW_HISTORY AS (
    SELECT 
        PH.USER_ID, PH.PENALTY_ID, PH.PENALTY_SCORE, PH.CREATED_AT,
        SUM(CASE WHEN PC.PENALTY_ID IS NULL THEN PH.PENALTY_SCORE ELSE 0 END) 
            OVER (PARTITION BY PH.USER_ID ORDER BY PH.CREATED_AT ASC) AS ACCUMULATED_SCORE,
        PC.PENALTY_ID AS CANCEL_ID, PC.CANCEL_REASON
    FROM PENALTY_HISTORY PH
    LEFT JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID
)
SELECT 
    UA.USER_LOGIN_ID,  -- [추가] 유저의 실제 로그인 아이디
    RH.USER_ID, RH.PENALTY_ID, RH.PENALTY_SCORE AS GIVEN_SCORE,
    RH.ACCUMULATED_SCORE AS ACCUMULATED_SCORE,
    FN_GET_USER_PENALTY_SCORE(RH.USER_ID) AS TOTAL_SCORE,
    
    -- ... (기존 CASE WHEN 문 동일) ...
    CASE 
        WHEN RH.CANCEL_ID IS NOT NULL THEN '취소완료'
        WHEN PS.PENALTY_END_DATE < SYSDATE THEN '기간만료'
        ELSE '제재 중'
    END AS HISTORY_STATUS
FROM RAW_HISTORY RH
LEFT JOIN PENALTY_STATUS PS ON RH.PENALTY_ID = PS.PENALTY_ID
JOIN USER_ACCOUNT UA ON RH.USER_ID = UA.USER_ID;




-- ○ 7. 신고 통합 조회 뷰
CREATE OR REPLACE VIEW VW_REPORT_LIST
AS
SELECT 
    -- 1. 신고 기본 정보
    RS.REPORT_SUBMISSION_ID AS "신고번호",
    RS.CREATED_AT           AS "신고일시",
    RT.REPORT_TARGET_NAME   AS "신고대상구분",
    RTYPE.REPORT_TYPE_NAME  AS "신고유형",
    RS.REPORT_REASON        AS "신고사유",

    -- 2. 신고자 정보
    RS.USER_ID              AS "신고자_ID",
    UP.USER_NAME            AS "신고자명",

    -- 3. 피신고 대상 정보 (상품 또는 경매)
    CASE 
        WHEN PR.PRODUCT_ID IS NOT NULL THEN '상품'
        WHEN AR.AUCTION_ID IS NOT NULL THEN '경매'
        ELSE '기타'
    END AS "카테고리",
    COALESCE(P.PRODUCT_RELEASE_NAME, A.AUCTION_TITLE) AS "신고대상명",
    COALESCE(PR.PRODUCT_ID, AR.AUCTION_ID)           AS "대상코드_ID",

    -- 4. 신고 처리 현황 (★ 핵심 수정 부분)
    -- 처리 결과가 없으면 '대기'로 표시하고, 결과 ID가 있으면 실제 이름을 가져옴
    COALESCE(RR.REPORT_RESULT_NAME, '대기') AS "처리결과",
    RP.PROCESS_REASON                     AS "처리내용",
    RP.PROCESSED_AT                       AS "처리일시",
    ADM.ADMIN_LOGIN_ID                    AS "담당관리자"

FROM REPORT_SUBMISSION RS
-- 신고 유형 및 대상 분류 (기본 정보)
LEFT JOIN REPORT_TARGET RT ON RS.REPORT_TARGET_ID = RT.REPORT_TARGET_ID
LEFT JOIN REPORT_TYPE RTYPE ON RS.REPORT_TYPE_ID = RTYPE.REPORT_TYPE_ID

-- 신고자 이름
LEFT JOIN USER_PROFILE UP ON RS.USER_ID = UP.USER_ID

-- 상품 신고 상세 (상품 테이블과 조인)
LEFT JOIN PRODUCT_REPORT PR ON RS.REPORT_SUBMISSION_ID = PR.REPORT_SUBMISSION_ID
LEFT JOIN PRODUCT P ON PR.PRODUCT_ID = P.PRODUCT_ID

-- 경매 신고 상세 (경매 테이블과 조인)
LEFT JOIN AUCTION_REPORT AR ON RS.REPORT_SUBMISSION_ID = AR.REPORT_SUBMISSION_ID
LEFT JOIN AUCTION_REGISTRATION A ON AR.AUCTION_ID = A.AUCTION_ID

-- ★ 신고 처리 정보 (이 조인이 끊기면 결과가 NULL로 나옴)
LEFT JOIN REPORT_PROCESS RP ON RS.REPORT_SUBMISSION_ID = RP.REPORT_SUBMISSION_ID
LEFT JOIN REPORT_RESULT RR ON RP.REPORT_RESULT_ID = RR.REPORT_RESULT_ID
LEFT JOIN ADMIN_ACCOUNT ADM ON RP.ADMIN_ACCOUNT_ID = ADM.ADMIN_ACCOUNT_ID;

-- ○ 8. 경매 입찰 현재 순위 조회 뷰
CREATE OR REPLACE VIEW VW_AUCTION_BID_RANK
AS
SELECT 
    AUCTION_ID, USER_ID, BID_PRICE, 
    TO_CHAR(BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS CURRENT_RANK,
    COUNT(*) OVER (PARTITION BY AUCTION_ID) AS TOTAL_BIDDERS
FROM AUCTION_BID_PARTICIPATION;

-- ○ 9. 미결제 낙찰 대상 조회 뷰
CREATE OR REPLACE VIEW VW_UNPAID_WINNING_TARGET
AS
SELECT 
     A.AUCTION_ID          AS "경매번호"
    ,A.AUCTION_TITLE       AS "경매제목"
    ,U.USER_ID             AS "낙찰자번호"
    ,UA.USER_LOGIN_ID      AS "낙찰자ID"
    ,B.BID_PRICE           AS "낙찰금액"
    ,W.CREATED_AT          AS "낙찰일시"
    ,W.BID_RESULT_ID       AS "낙찰결과번호"
FROM AUCTION_WINNING_RESULT W
JOIN AUCTION_BID_PARTICIPATION B ON W.BID_ID = B.BID_ID
JOIN AUCTION_REGISTRATION A     ON B.AUCTION_ID = A.AUCTION_ID
JOIN USERS U                    ON B.USER_ID = U.USER_ID
JOIN USER_ACCOUNT UA            ON U.USER_ID = UA.USER_ID
WHERE NOT EXISTS (
    -- 이미 결제가 완료된 건 제외
    SELECT 1 
    FROM AUCTION_WINNING_PAYMENT P 
    WHERE P.BID_RESULT_ID = W.BID_RESULT_ID
)
AND NOT EXISTS (
    -- 이미 낙찰 실패 처리가 된 건 제외
    SELECT 1 
    FROM BID_FAILURE_HISTORY F 
    WHERE F.BID_RESULT_ID = W.BID_RESULT_ID
);


-- ○ 10. 경매 마감 임박 순서 뷰
CREATE OR REPLACE VIEW VW_AUCTION_URGENT_LIST
AS
SELECT VA.AUCTION_ID, VA.AUCTION_TITLE, VA.IMAGE_PATH_1, VA.BID_CURRENT_PRICE, UA.USER_LOGIN_ID, VA.AUCTION_END_DATE
   , ROW_NUMBER() OVER(ORDER BY VA.AUCTION_END_DATE DESC) AS RK
FROM VW_AUCTION_LIST VA 
    JOIN PRODUCT P ON VA.PRODUCT_ID = P.PRODUCT_ID
    JOIN USER_ACCOUNT UA ON P.USER_ID = UA.USER_ID
WHERE TO_DATE(AUCTION_END_DATE,'YYYY-MM-DD HH24:MI:SS') > SYSDATE;


-- ○ 11. 머니 거래 내역 조회 뷰
CREATE OR REPLACE VIEW VW_MONEY_HISTORY
AS
SELECT 
    USER_ID,
    '충전' AS TRANSACTION_TYPE, 
    CHARGE_AMOUNT AS AMOUNT,     
    TO_CHAR(CHARGED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MCM.MONEY_CHARGE_METHOD_NAME AS DESCRIPTION 
FROM MONEY_CHARGE_HISTORY MCH
JOIN MONEY_CHARGE_METHOD MCM ON MCH.MONEY_CHARGE_METHOD_ID = MCM.MONEY_CHARGE_METHOD_ID
UNION ALL
SELECT 
    USER_ID,
    MT.MONEY_TYPE_NAME AS TRANSACTION_TYPE, 
    AMOUNT,                 
    TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MT.MONEY_TYPE_NAME AS DESCRIPTION     
FROM MONEY_TRANSACTION_HISTORY MTH
JOIN MONEY_TYPE MT ON MTH.MONEY_TYPE_ID = MT.MONEY_TYPE_ID;


-- ○ 12. 관리자 유저 조회 뷰
CREATE OR REPLACE VIEW VIEW_ADMIN_USER_LIST
AS
SELECT 
    U.USER_ID AS USERKEY           
    , A.USER_LOGIN_ID AS USERID    
    , P.USER_NAME AS USERNAME      
    , P.USER_PHONE AS USERTEL      
    -- 가입일이 없으면 오늘 날짜라도 나오게 처리
    , NVL((SELECT TO_CHAR(MIN(H.CREATED_AT), 'YYYY-MM-DD') 
           FROM ACCOUNT_EVENT_HISTORY H 
           WHERE H.USER_ID = U.USER_ID), TO_CHAR(SYSDATE, 'YYYY-MM-DD')) AS USERCREATED
    , CASE 
        WHEN S.PENALTY_STATUS_ID IS NOT NULL THEN '제재중'
        ELSE '정상'
      END AS USERSTATUS            
FROM USERS U
LEFT JOIN USER_ACCOUNT A ON U.USER_ID = A.USER_ID  
LEFT JOIN USER_PROFILE P ON U.USER_ID = P.USER_ID  
LEFT JOIN (
    SELECT PH.USER_ID, PS.PENALTY_STATUS_ID
    FROM PENALTY_HISTORY PH
    JOIN PENALTY_STATUS PS ON PH.PENALTY_ID = PS.PENALTY_ID
    WHERE CURRENT_DATE BETWEEN PS.PENALTY_START_DATE AND PS.PENALTY_END_DATE
) S ON U.USER_ID = S.USER_ID;

-- ○ 13. 관리자 유저 상세조회 뷰
CREATE OR REPLACE VIEW VIEW_USER_INFO
AS
SELECT 
    U.USER_ID
    , UA.USER_LOGIN_ID
    , UA.USER_PASSWORD
    , UP.USER_NAME
    , UP.USER_SSN
    , UP.USER_EMAIL
    , UP.USER_PHONE
    , UP.USER_ZIPCODE
    , UP.USER_ADDRESS
    , UP.USER_ADDRESS_DETAIL
    , FN_GET_USER_MONEY_BALANCE(U.USER_ID) AS TOTAL_MONEY
    -- 1. 가입일시 추가 (이력 테이블에서 최초 발생일 가져오기, 없을 시 현재날짜)
    , NVL((SELECT TO_CHAR(MIN(H.CREATED_AT), 'YYYY-MM-DD HH24:MI:SS') 
           FROM ACCOUNT_EVENT_HISTORY H 
           WHERE H.USER_ID = U.USER_ID), TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')) AS CREATED_AT
    -- 2. 계정 상태 추가 (패널티 이력 확인)
    , CASE 
        WHEN S.PENALTY_STATUS_ID IS NOT NULL THEN '제재중'
        ELSE '정상'
      END AS USER_STATUS
FROM USERS U 
LEFT JOIN USER_ACCOUNT UA ON U.USER_ID = UA.USER_ID
LEFT JOIN USER_PROFILE UP ON U.USER_ID = UP.USER_ID
LEFT JOIN (
    -- 현재 활성화된 패널티가 있는지 확인하기 위한 조인용 서브쿼리
    SELECT PH.USER_ID, PS.PENALTY_STATUS_ID
    FROM PENALTY_HISTORY PH
    JOIN PENALTY_STATUS PS ON PH.PENALTY_ID = PS.PENALTY_ID
    WHERE CURRENT_DATE BETWEEN PS.PENALTY_START_DATE AND PS.PENALTY_END_DATE
) S ON U.USER_ID = S.USER_ID;



