select user from dual;

-- 예시 데이터 생성
-- ============================================================
DELETE FROM AUCTION_WINNING_RESULT;
DELETE FROM AUCTION_BID_PARTICIPATION;
DELETE FROM AUCTION_REGISTRATION;
DELETE FROM PRODUCT;
DELETE FROM USER_PROFILE;
DELETE FROM USERS;
DELETE FROM AUCTION_PERIOD;
DELETE FROM PRODUCT_GRADE;
DELETE FROM PRODUCT_GENRE;
DELETE FROM PRODUCT_SIZE;
DELETE FROM PRODUCT_MANUFACTURER;
DELETE FROM PRODUCT_COUNTRY;

-- ============================================================
-- 1. USERS
-- ============================================================
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL);
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL);
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL);
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL);
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL);

SELECT *
FROM USERS
-- ※ 위 INSERT 후 실제 생성된 USER_ID 값을 반드시 확인하세요.
--   아래 SQL로 현재 시퀀스 값 확인:
--   SELECT USERS_SEQ.CURRVAL FROM DUAL;
-- 이하 스크립트는 USER_ID가 1~5로 생성되었다고 가정합니다.
-- 다를 경우 아래 전체의 USER_ID 값을 실제 값으로 변경하세요.


-- ============================================================
-- 2. USER_ACCOUNT
-- ============================================================
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD)
VALUES (1, 'kim_minsu', 'Hashed!pw001');
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD)
VALUES (2, 'lee_jiyeon', 'Hashed!pw002');
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD)
VALUES (6, 'park_junho', 'Hashed!pw003');
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD)
VALUES (4, 'choi_soyeon', 'Hashed!pw004');
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD)
VALUES (5, 'jung_hyunwoo', 'Hashed!pw005');

SELECT *
FROM USER_ACCOUNT
-- ============================================================
-- 3. USER_PROFILE
--    USER_SSN: 하이픈 제거 13자리 (YYMMDD + 뒷자리7)
--    예) '9001011000001' (생년월일6 + 성별1 + 마스킹6)
-- ============================================================
INSERT INTO USER_PROFILE (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (1, '김민수', '9001011000001', 'minsu.kim@email.com', '01012345678', '06234', '서울특별시 강남구 테헤란로 123', '101동 501호');
INSERT INTO USER_PROFILE (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (2, '이지연', '9212152000002', 'jiyeon.lee@email.com', '01023456789', '03722', '서울특별시 서대문구 연세로 50', '빌라 302호');
INSERT INTO USER_PROFILE (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (4, '박준호', '8805301000003', 'junho.park@email.com', '01034567890', '14056', '경기도 안양시 동안구 평촌대로 200', '센트럴파크 704호');
INSERT INTO DELETED_USER (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (5, '최소연', '9508202000004', 'soyeon.choi@email.com', '01045678901', '48060', '부산광역시 해운대구 해운대로 30', '오션타워 1201호');
INSERT INTO DELETED_USER (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (6, '정현우', '8703141000005', 'hyunwoo.jung@email.com', '01056789012', '21565', '인천광역시 남동구 인하로 100', '주공아파트 203동 405호');

SELECT *
FROM USER_PROFILE;
-- ============================================================
-- 4. DELETED_USER
-- ============================================================
INSERT INTO DELETED_USER (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (6, '최소연', '9508202000004', 'soyeon.choi@email.com', '01045678901', '48060', '부산광역시 해운대구 해운대로 30', '오션타워 1201호');
INSERT INTO DELETED_USER (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (7, '정현우', '8703141000005', 'hyunwoo.jung@email.com', '01056789012', '21565', '인천광역시 남동구 인하로 100', '주공아파트 203동 405호');


-- ============================================================
-- 6. ACCOUNT_EVENT_HISTORY
--    시퀀스명: ACCOUNT_EVENT_HISTORY_SEQ (범례 스크립트 네이밍 패턴 기준)
--    실제 시퀀스명이 다를 경우 수정 필요
-- ============================================================
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 3, 6);
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 4, 6, TO_DATE('2023-05-12', 'YYYY-MM-DD'));
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 5, 6, TO_DATE('2023-07-20', 'YYYY-MM-DD'));
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 6, 6, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 7, 6, TO_DATE('2024-01-15', 'YYYY-MM-DD'));
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 6, 7, TO_DATE('2024-06-10', 'YYYY-MM-DD'));
INSERT INTO ACCOUNT_EVENT_HISTORY (ACCOUNT_EVENT_ID, USER_ID, ACCOUNT_EVENT_TYPE_ID, CREATED_AT)
VALUES (ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, 7, 7, TO_DATE('2024-08-22', 'YYYY-MM-DD'));


-- ============================================================
-- 8. ADMIN_ACCOUNT
--    패스워드 체크 제약(ADMIN_ACCOUNT_PW_CK) 대응:
--    대문자 + 소문자 + 숫자 + 특수문자 조합으로 작성
--    실제 제약 조건에 따라 형식이 다를 수 있으니 DDL 확인 후 수정
SELECT *
FROM ADMIN_ACCOUNT;

SELECT *
FROM ADMIN_ROLE;
-- ============================================================
INSERT INTO ADMIN_ACCOUNT (ADMIN_ACCOUNT_ID, ADMIN_ROLE_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD)
VALUES (ADMIN_ACCOUNT_SEQ.NEXTVAL, 3, 'superadmin', 'Admin@12345');
INSERT INTO ADMIN_ACCOUNT (ADMIN_ACCOUNT_ID, ADMIN_ROLE_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD)
VALUES (ADMIN_ACCOUNT_SEQ.NEXTVAL, 4, 'admin_yoon', 'Admin@22345');
INSERT INTO ADMIN_ACCOUNT (ADMIN_ACCOUNT_ID, ADMIN_ROLE_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD)
VALUES (ADMIN_ACCOUNT_SEQ.NEXTVAL, 4, 'admin_han', 'Admin@32345');

-- ※ 위 패스워드도 오류 날 경우 ADMIN_ACCOUNT 테이블 DDL에서
--   ADMIN_ACCOUNT_PW_CK 제약 조건 내용을 확인하고 맞춰주세요:
--   SELECT SEARCH_CONDITION FROM USER_CONSTRAINTS
--   WHERE CONSTRAINT_NAME = 'ADMIN_ACCOUNT_PW_CK';


-- ============================================================
-- 9. ADMIN_PROFILE
--    EMPLOYEE_ID 숫자형(NUMBER)으로 수정
-- ============================================================
INSERT INTO ADMIN_PROFILE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT)
VALUES (1, '윤상철', '시스템관리팀');
INSERT INTO ADMIN_PROFILE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT)
VALUES (2, '한미래', '고객서비스팀');
INSERT INTO ADMIN_PROFILE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT)
VALUES (3, '오진석', '고객서비스팀');


-- ============================================================
-- 10. ADMIN_ACCOUNT_HISTORY
--     EMPLOYEE_ID 숫자형으로 수정
-- ============================================================
INSERT INTO ADMIN_ACCOUNT_HISTORY (ADMIN_HISTORY_ID, ADMIN_ACCOUNT_ID, EMPLOYEE_ID, ACCOUNT_START_DATE, ACCOUNT_END_DATE)
VALUES (ADMIN_HISTORY_SEQ.NEXTVAL, 11, 1, TO_DATE('2022-01-03', 'YYYY-MM-DD'), NULL);
INSERT INTO ADMIN_ACCOUNT_HISTORY (ADMIN_HISTORY_ID, ADMIN_ACCOUNT_ID, EMPLOYEE_ID, ACCOUNT_START_DATE, ACCOUNT_END_DATE)
VALUES (ADMIN_HISTORY_SEQ.NEXTVAL, 12, 2, TO_DATE('2022-03-07', 'YYYY-MM-DD'), NULL);
INSERT INTO ADMIN_ACCOUNT_HISTORY (ADMIN_HISTORY_ID, ADMIN_ACCOUNT_ID, EMPLOYEE_ID, ACCOUNT_START_DATE, ACCOUNT_END_DATE)
VALUES (ADMIN_HISTORY_SEQ.NEXTVAL, 13, 3, TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2024-05-31', 'YYYY-MM-DD'));


-- ============================================================
-- 17. PRODUCT
--    IS_OPENED, IS_PARTS_MISSING, IS_PUBLIC: COMMON_YN_ID FK (0=N, 1=Y)
--    IMAGE_PATH_1/2/3: NOT NULL이므로 모두 더미 경로로 채움
SELECT *
FROM PRODUCT_SIZE
SELECT *
FROM PRODUCT_GENRE
SELECT *
FROM PRODUCT_GRADE
SELECT *
FROM PRODUCT_MANUFACTURER
-- ============================================================
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID,
    MANUFACTURER_ID, PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID,
    WORK_NAME, CHARACTER_NAME, PURCHASE_DATETIME,
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS,
    IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC, CREATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL,
    'Hot Toys MMS576 Iron Man Mark III', '아이언맨 MK3 1/6',
    5, 8, 1, 1, 1,
    '아이언맨', '아이언맨(토니 스타크)',
    TO_TIMESTAMP('2021-08-15 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    1, 0,
    '핫토이 아이언맨 MK3 피규어입니다. 개봉 후 진열만 하였으며 파츠 결품 없음. 박스 상태 양호.',
    '/images/products/1/main.jpg', '/images/products/1/side.jpg', '/images/products/1/back.jpg',
    1, TO_TIMESTAMP('2024-02-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID,
    MANUFACTURER_ID, PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID,
    WORK_NAME, CHARACTER_NAME, PURCHASE_DATETIME,
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS,
    IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC, CREATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL,
    'Good Smile Company Hatsune Miku 1/4', '하츠네 미쿠 1/4 스케일',
    6, 2, 2, 2, 2,
    '보컬로이드', '하츠네 미쿠',
    TO_TIMESTAMP('2022-11-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    1, 0,
    '굿스마일 컴퍼니 공식 1/4 스케일. 미개봉에 가까운 상태. 박스 일부 모서리 눌림 있음.',
    '/images/products/2/main.jpg', '/images/products/2/angle.jpg', '/images/products/2/angle2.jpg',
    1, TO_TIMESTAMP('2024-03-05 11:30:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID,
    MANUFACTURER_ID, PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID,
    WORK_NAME, CHARACTER_NAME, PURCHASE_DATETIME,
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS,
    IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC, CREATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL,
    'Bandai S.H.Figuarts Goku Ultra Instinct', '손오공 극의 피규어',
    1, 4, 2, 2, 1,
    '드래곤볼 슈퍼', '손오공(극의)',
    TO_TIMESTAMP('2023-04-01 16:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    1, 0,
    '개봉 후 포즈 변경 1회. 오리지널 파츠 완비. 박스 보관 상태 양호.',
    '/images/products/3/main.jpg', '/images/products/3/side.jpg', '/images/products/3/back.jpg',
    1, TO_TIMESTAMP('2024-04-18 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID,
    MANUFACTURER_ID, PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID,
    WORK_NAME, CHARACTER_NAME, PURCHASE_DATETIME,
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS,
    IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC, CREATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL,
    'Sideshow Premium Format Batman Arkham', '배트맨 프리미엄 포맷',
    2, 4, 3, 1, 1,
    '배트맨: 아캄 나이트', '배트맨',
    TO_TIMESTAMP('2020-05-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    1, 1,
    '진열 사용. 케이프 일부 파츠 분실 있음(설명 참조). 가격 반영됨.',
    '/images/products/4/main.jpg', '/images/products/4/detail.jpg', '/images/products/4/back.jpg',
    1, TO_TIMESTAMP('2024-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID,
    MANUFACTURER_ID, PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID,
    WORK_NAME, CHARACTER_NAME, PURCHASE_DATETIME,
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS,
    IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC, CREATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL,
    'Kotobukiya ARTFX J Link Breath of the Wild', '링크 브레스 오브 더 와일드',
    4, 4, 5, 2, 2,
    '젤다의 전설: 야숨', '링크',
    TO_TIMESTAMP('2023-10-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    0, 0,
    '미개봉 새제품. 국내 정식발매 구매. 박스 완전 밀봉 상태.',
    '/images/products/5/main.jpg', '/images/products/5/box.jpg', '/images/products/5/box2.jpg',
    1, TO_TIMESTAMP('2024-06-10 17:00:00', 'YYYY-MM-DD HH24:MI:SS'));


-- ============================================================
-- 18. PRODUCT_IMAGE
SELECT *
FROM PRODUCT
-- ============================================================
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH, CREATED_AT)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, 2, 1, '/images/products/1/extra1.jpg', TO_DATE('2026-04-24', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH, CREATED_AT)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, 5, 5, '/images/products/1/extra2.jpg', TO_DATE('SYSDATE', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH, CREATED_AT)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, 31, 4, '/images/products/2/extra1.jpg', TO_DATE('2024-03-05', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH, CREATED_AT)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, 32, 4, '/images/products/4/extra1.jpg', TO_DATE('2024-05-01', 'YYYY-MM-DD'));


-- ============================================================
-- 19. PRODUCT_WISHLIST
-- ============================================================
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 5, 29, TO_DATE('2024-02-12', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 5, 33, TO_DATE('2024-04-20', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 5, 31, TO_DATE('2024-03-10', 'YYYY-MM-DD'));

INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 6, 30, TO_DATE('2024-02-14', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 7, 31, TO_DATE('2024-03-10', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 8, 32, TO_DATE('2024-06-15', 'YYYY-MM-DD'));
INSERT INTO PRODUCT_WISHLIST (WISHLIST_ID, USER_ID, PRODUCT_ID, CREATED_AT)
VALUES (WISHLIST_SEQ.NEXTVAL, 9, 33, TO_DATE('2024-04-20', 'YYYY-MM-DD'));



-- ============================================================
-- 22. MONEY_CHARGE_HISTORY
SELECT *
FROM MONEY_CHARGE_METHOD
-- ============================================================
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT, CHARGED_AT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 5, 6, 500000, TO_DATE('2024-02-08', 'YYYY-MM-DD'));
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT, CHARGED_AT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 6, 5, 1000000, TO_DATE('2024-03-01', 'YYYY-MM-DD'));
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT, CHARGED_AT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 7, 6, 300000, TO_DATE('2024-04-10', 'YYYY-MM-DD'));
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT, CHARGED_AT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 8, 6, 800000, TO_DATE('2024-06-08', 'YYYY-MM-DD'));
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT, CHARGED_AT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 9, 5, 200000, TO_DATE('2024-01-20', 'YYYY-MM-DD'));


-- ============================================================
-- 24. AUCTION_REGISTRATION
SELECT *
FROM AUCTION_PERIOD
-- ============================================================
INSERT INTO AUCTION_REGISTRATION (AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, START_PRICE, CREATED_AT, AUCTION_PERIOD_ID)
VALUES (AUCTION_SEQ.NEXTVAL, 1,
    '[핫토이] 아이언맨 MK3 1/6 판매합니다',
    '개봉 진열품이나 상태 최상입니다. 파츠 완비. 직거래 불가, 안전배송 포장하여 발송합니다.',
    350000, TO_TIMESTAMP('2026-04-23 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

INSERT INTO AUCTION_REGISTRATION (AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, START_PRICE, CREATED_AT, AUCTION_PERIOD_ID)
VALUES (AUCTION_SEQ.NEXTVAL, 5,
    '[굿스마일] 하츠네 미쿠 1/4 스케일 경매',
    '박스 모서리 눌림 외 본품 상태 양호. 시작가 낮게 설정합니다.',
    180000, TO_TIMESTAMP('2026-04-24 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);

INSERT INTO AUCTION_REGISTRATION (AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, START_PRICE, CREATED_AT, AUCTION_PERIOD_ID)
VALUES (AUCTION_SEQ.NEXTVAL, 6,
    '[반다이] 손오공 극의 SHF 경매',
    '개봉 후 포즈 변경 1회. 파츠 완비. 7일 경매로 진행합니다.',
    45000, TO_TIMESTAMP(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 2);

INSERT INTO AUCTION_REGISTRATION (AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, START_PRICE, CREATED_AT, AUCTION_PERIOD_ID)
VALUES (AUCTION_SEQ.NEXTVAL, 32,
    '[코토부키야] 링크 야숨 미개봉 경매',
    '미개봉 새제품. 정식발매 구매. 세금계산서 발행 불가.',
    120000, TO_TIMESTAMP('2024-07-10 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 22);


-- ============================================================
-- 25. MONEY_TRANSACTION_HISTORY
--    시퀀스명: MONEY_TRANSACTION_HISTORY_SEQ 로 수정
SELECT *
FROM MONEY_TYPE
-- ============================================================
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 5, 2, 19, 35000, TO_TIMESTAMP('2024-07-01 10:01:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 6, 2, 2, 18000, TO_TIMESTAMP('2024-07-03 12:01:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 7, 3, 1, 35000, TO_TIMESTAMP('2024-07-02 11:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 7, 1, 1, 420000, TO_TIMESTAMP('2024-07-04 09:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 5, 7, 1, 420000, TO_TIMESTAMP('2024-07-04 09:35:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 5, 4, 1, 35000, TO_TIMESTAMP('2024-07-04 09:36:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MONEY_TRANSACTION_HISTORY (MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT)
VALUES (MONEY_TRANSACTION_HISTORY_SEQ.NEXTVAL, 7, 5, 1, 35000, TO_TIMESTAMP('2024-07-04 09:36:00', 'YYYY-MM-DD HH24:MI:SS'));


-- ============================================================
-- 26. AUCTION_CANCEL_HISTORY
-- ============================================================
INSERT INTO AUCTION_CANCEL_HISTORY (AUCTION_CANCEL_ID, AUCTION_ID, CANCEL_REASON, CANCEL_AT)
VALUES (AUCTION_CANCEL_SEQ.NEXTVAL, 4,
    '판매자 사정으로 인한 경매 취소 요청',
    TO_DATE('2024-07-11', 'YYYY-MM-DD'));


-- ============================================================
-- 27. AUCTION_BID_PARTICIPATION
SELECT *
FROM AUCTION_REGISTRATION
-- ============================================================
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 1, 5, SYSDATE, 360000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 2, 5, SYSDATE, 380000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 4, 5, SYSDATE, 420000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 5, 5, SYSDATE, 200000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 6, 5, SYSDATE, 220000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 1, 5, SYSDATE, 50000);

INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 1, 2, SYSDATE, 360000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 2, 2, SYSDATE, 380000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 4, 2, SYSDATE, 420000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 5, 2, SYSDATE, 200000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 6, 2, SYSDATE, 220000);
INSERT INTO AUCTION_BID_PARTICIPATION (BID_ID, USER_ID, AUCTION_ID, BID_TIME, BID_PRICE)
VALUES (BID_SEQ.NEXTVAL, 1, 2, SYSDATE, 50000);


-- ============================================================
-- 28. AUCTION_WINNING_RESULT
--     BID_ID=3 (USER_ID=3, 경매1, 420,000원 최고가)
SELECT *
FROM AUCTION_BID_PARTICIPATION
SELECT *
FROM AUCTION_WINNING_RESULT
SELECT *
FROM AUCTION_REGISTRATION
SELECT *
FROM AUCTION_PERIOD;
SELECT * FROM MONEY_TYPE;
SELECT *
FROM MONEY_TRANSACTION_HISTORY;
SELECT *
FROM AUCTION_WINNING_PAYMENT;
SELECT *
FROM DELIVERY_COMPLETED;
SELECT *
FROM MONEY_TRANSACTION_HISTORY;
INSERT INTO DELIVERY_COMPLETED(SHIPPING_ID,PAYMENT_ID)
VALUES(SHIPPING_SEQ.NEXTVAL,1)
SELECT *
FROM MONEY_CHARGE_HISTORY;
SELECT *
FROM USERS;
-- ============================================================

INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT)
VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,1,3,5,40000);
SELECT *
FROM USER_SEQUENCES;
INSERT INTO AUCTION_WINNING_RESULT (BID_RESULT_ID, BID_ID, CREATED_AT)
VALUES (BID_RESULT_SEQ.NEXTVAL, 22, TO_TIMESTAMP('2024-07-04 09:00:05', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO AUCTION_WINNING_RESULT (BID_RESULT_ID, BID_ID, CREATED_AT)
VALUES (BID_RESULT_SEQ.NEXTVAL, 28, TO_TIMESTAMP('2026-04-24 08:00:05', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO AUCTION_WINNING_RESULT (BID_RESULT_ID, BID_ID, CREATED_AT)
VALUES (BID_RESULT_SEQ.NEXTVAL, 56, TO_TIMESTAMP('2026-04-24 08:00:05', 'YYYY-MM-DD HH24:MI:SS'));


UPDATE AUCTION_WINNING_RESULT
SET CREATED_AT = TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
WHERE BID_ID =22;
COMMIT;


---------------------------------------------------------------------------------------------------------

-- 낙찰 결제 프로시저(컴파일O,테스트O)
CREATE OR REPLACE PROCEDURE PRC_WINNING_PAYMENT_CREATE
(
    V_USER_ID USERS.USER_ID%TYPE
    ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
    ,V_AMOUNT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE
)
AS
    N_BID_ID AUCTION_WINNING_RESULT.BID_ID%TYPE;
    N_AUCTION_ID AUCTION_BID_PARTICIPATION.AUCTION_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;
    N_MONEY_TYPE MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;

    N_AUCTION_PERIOD_ID AUCTION_PERIOD.AUCTION_PERIOD_ID%TYPE;
    N_AUCTION_PERIOD_NAME AUCTION_PERIOD.AUCTION_PERIOD_NAME%TYPE;
    
    N_END_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    N_START_PRICE AUCTION_REGISTRATION.START_PRICE%TYPE;
    
    N_AUCTION_PRICE AUCTION_BID_PARTICIPATION.BID_PRICE%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
BEGIN
 
    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT AUCTION_ID,USER_ID INTO N_AUCTION_ID,N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT CREATED_AT,AUCTION_PERIOD_ID,START_PRICE INTO N_CREATE_AT,N_AUCTION_PERIOD_ID,N_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = N_AUCTION_ID;
    
    SELECT AUCTION_PERIOD_NAME INTO N_AUCTION_PERIOD_NAME
    FROM AUCTION_PERIOD
    WHERE AUCTION_PERIOD_ID = N_AUCTION_PERIOD_ID;
    
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'일','');
    
    N_END_CREATE_AT := N_CREATE_AT + TO_NUMBER(TRIM(N_AUCTION_PERIOD_NAME)) + 1;
    
    IF(N_END_CREATE_AT < SYSTIMESTAMP)
        THEN RAISE NEW_ERR;
    END IF;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID
    ,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID
    ,N_MONEY_TYPE,N_AUCTION_ID,V_AMOUNT);
    
    INSERT INTO AUCTION_WINNING_PAYMENT(PAYMENT_ID
    ,BID_RESULT_ID,MONEY_ID)
    VALUES(PAYMENT_SEQ.NEXTVAL,V_RESULT_ID
    ,MONEY_TRANSACTION_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20100,'결제기간이 마감되어 결제가 불가능합니다');
        
        WHEN NEW_ERR1
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;


-- 구매 확정 및 거래 완료 프로시저(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_PURCHASE_CONFIRM
(
    V_USER_ID USERS.USER_ID%TYPE
    ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
)
IS
    N_PAYMENT_ID AUCTION_WINNING_PAYMENT.PAYMENT_ID%TYPE;
    N_SHIPPING_ID DELIVERY_COMPLETED.SHIPPING_ID%TYPE;
    
    N_BID_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;  -- 구매자 검증 아이디

    N_USER_ID2 USERS.USER_ID%TYPE; -- 판매자 아이디

    N_MONEY_TYPE1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE5 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE6 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
    NEW_ERR2 EXCEPTION;
BEGIN
    
    
    SELECT NVL(PAYMENT_ID,0) INTO N_PAYMENT_ID
    FROM AUCTION_WINNING_PAYMENT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_PAYMENT_ID = 0)
        THEN RAISE NEW_ERR;
    END IF;
    
    SELECT NVL(SHIPPING_ID,0) INTO N_SHIPPING_ID
    FROM DELIVERY_COMPLETED
    WHERE PAYMENT_ID = N_PAYMENT_ID;
    
    IF(N_SHIPPING_ID = 0)
        THEN RAISE NEW_ERR2;
    END IF;

    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT USER_ID INTO N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;

    -- 구매 확정
    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    VALUES(PURCHASE_CONFIRM_SEQ.NEXTVAL,N_SHIPPING_ID);
    
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE5
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE6
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금';
    
    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_MONEY_TYPE3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;
    
    IF(N_MONEY_TYPE5 = 0)
        THEN RAISE_APPLICATION_ERROR(-20112,'머니 분류 테이블에 "결제" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE6 = 0)
        THEN RAISE_APPLICATION_ERROR(-20113,'머니 분류 테이블에 "결제 대금" 코드명이 존재하지 않습니다');
    END IF;

    -- 구매자 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE1,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE3;

    -- 판매자 아이디
    SELECT USER_ID INTO N_USER_ID2
    FROM AUCTION_REGISTRATION A JOIN PRODUCT B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE AUCTION_ID = N_AUCTION_ID;

    -- 판매자 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE2,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = N_USER_ID2
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE4; 
    
    -- 구매대금 판매자에게 이력추가 V_USER_ID
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,N_USER_ID2,N_MONEY_TYPE_ID6,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = V_USER_ID
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID5;
    
    -- 거래완료 
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    VALUES(TRANSACTION_SEQ.NEXTVAL,PURCHASE_CONFIRM_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20102,'입금되지않은 낙찰입니다.');

        WHEN NEW_ERR1
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        -- (구매확정)결제자 와 (낙찰)입찰자
        
        WHEN NEW_ERR2
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'발송되지않은 낙찰입니다.');

        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;


--결제 -
--판매 보증금 납부 -
--구매 보증금 납부 -
--판매 보증금 환급 +
--구매 보증금 환급 +
--결제 취소(환불)
--결제 대금 입금 - 
--보증금 몰수 (금액은 0으로 두고 이력처리)

-- 회원 잔여 머니 조회 함수(컴파일O,테스트X)
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(
    V_USER_ID USERS.USER_ID%TYPE
)
RETURN NUMBER
AS
    RESULT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
    CHARGE_MONEY MONEY_CHARGE_HISTORY.CHARGE_AMOUNT%TYPE;
    MINUS_MONEY MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
    PLUS_MONEY MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
    
BEGIN
    RESULT := 0;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO CHARGE_MONEY
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = V_USER_ID;
    
    RESULT := RESULT+NUMBER(CHARGE_MONEY);
    
    SELECT NVL(SUM(A.AMOUNT),0) INTO MINUS_MONEY
    FROM MONEY_TRANSACTION_HISTORY A LEFT JOIN MONEY_TYPE B
    ON A.MONEY_TYPE_ID = B.MONEY_TYPE_ID
    WHERE A.USER_ID = V_USER_ID
    AND B.MONEY_TYPE_NAME IN ('결제','판매 보증금 납부','구매 보증금 납부'
    ,'결제 대금');
    
    RESULT := RESULT-MINUS_MONEY;
    
    SELECT NVL(SUM(A.AMOUNT),0) INTO PLUS_MONEY
    FROM MONEY_TRANSACTION_HISTORY A LEFT JOIN MONEY_TYPE B
    ON A.MONEY_TYPE_ID = B.MONEY_TYPE_ID
    WHERE A.USER_ID = V_USER_ID
    AND B.MONEY_TYPE_NAME IN ('판매 보증금 환급','구매 보증금 환급');
    
    RESULT := RESULT+PLUS_MONEY;
    
    RETURN RESULT;
END;

-- 낙찰 실패 처리 프로시저(낙찰 취소 처리 프로시저, 실패는 스케줄러로만)
CREATE OR REPLACE PROCEDURE PRC_BID_FAILURE_PROCESS
(
   V_USER_ID USERS.USER_ID%TYPE
   ,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
   
)
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_PENALTY_TYPE_ID PENALTY_ASSIGN_TYPE.PENALTY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    V_TOTAL_PENALTY_SCORE       PENALTY_HISTORY.PENALTY_SCORE%TYPE;
    V_PENALTY_END_DATE          PENALTY_STATUS.PENALTY_END_DATE%TYPE;
    N_PENALTY_ID                PENALTY_HISTORY.PENALTY_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '낙찰포기';

    -- 낙찰 실패 이력
    INSERT INTO BID_FAILURE_HISTORY(BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    VALUES(BID_FAIL_HISTORY_SEQ.NEXTVAL,V_RESULT_ID,N_BID_FAIL_TYPE_ID);

    SELECT NVL(PENALTY_TYPE_ID,0) INTO N_PENALTY_TYPE_ID
    FROM PENALTY_ASSIGN_TYPE
    WHERE PENALTY_TYPE_NAME = '자동';

    N_PENALTY_ID := PENALTY_SEQ.NEXTVAL;
    
    -- 구매자 패널티 부여
    INSERT INTO PENALTY_HISTORY(PENALTY_ID,USER_ID,PENALTY_TYPE_ID,ADMIN_ACCOUNT_ID,PENALTY_SCORE)
    VALUES(N_PENALTY_ID,V_USER_ID,N_PENALTY_TYPE_ID,NULL,1);
    
    SELECT SUM(PH.PENALTY_SCORE) INTO V_TOTAL_PENALTY_SCORE
    FROM PENALTY_HISTORY PH LEFT OUTER JOIN PENALTY_CANCEL PC
         ON PH.PENALTY_ID = PC.PENALTY_ID
    WHERE PH.USER_ID = V_USER_ID
      AND PENALTY_CANCEL_ID IS NULL;
   
    -- 패널티 점수가 일정치 이상(1점 초과)이면 제재 발생
    IF V_TOTAL_PENALTY_SCORE > 1 THEN
        CASE
            -- 4점 이상: 영구 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 4
            THEN V_PENALTY_END_DATE := TO_DATE('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

            -- 3점 이상: 30일 정지
            -- 오늘을 기준으로 30일 뒤 23시59분59초까지 계정 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 3
            THEN V_PENALTY_END_DATE := TRUNC(SYSDATE + 30) + (1 - 1/86400);

            -- 그 외(2점 이상): 7일 정지
            -- 오늘을 기준으로 7일 뒤 23시59분59초까지 계정 정지
            ELSE V_PENALTY_END_DATE := TRUNC(SYSDATE + 7) + (1 - 1/86400);
        END CASE;

        INSERT INTO PENALTY_STATUS (PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE)
        VALUES (PENALTY_STATUS_SEQ.NEXTVAL, N_PENALTY_ID, SYSDATE, V_PENALTY_END_DATE);
    END IF;



    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A INNER JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID AND B.USER_ID = V_USER_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;

    -- 구매자 보증금 몰수
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID,N_MONEY_TYPE_ID1,N_AUCTION_ID,0);

    -- 이외 구매자 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE_ID3,N_AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    AND USER_ID != V_USER_ID;

    -- 판매자 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE_ID4,N_AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE_ID;

    COMMIT;

    EXCEPTION 
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;

-- 트리거 삭제(낙찰실패에 트리거랑 충돌,프로시저로 통합 모든 패널티부여시 프로시저생성시 트리거 역할 넣어야함)
DROP TRIGGER TRG_PENALTY_AFTER_INS;

SELECT *
FROM PENALTY_HISTORY;

-- 낙찰 결제 기한 확인 스케줄러(컴파일O,테스트X)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
    JOB_NAME => 'SCH_AUCTION_CLOSE'
    ,JOB_TYPE => 'STORED_PROCEDURE'
    ,JOB_ACTION => 'REC_AUCTION_CLOSE'
    ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
    ,ENABLED => FALSE
    );
END;

-- 낙찰 결제 기한 확인 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE REC_AUCTION_CLOSE
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_PENALTY_TYPE_ID PENALTY_ASSIGN_TYPE.PENALTY_TYPE_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '결제기한만료';
    
    IF(N_BID_FAIL_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "결제기한만료" 코드명이 존재하지 않습니다');
    END IF;

    -- 낙찰 실패 이력
    INSERT INTO (BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    SELECT BID_FAIL_HISTORY_SEQ.NEXTVAL,M.BID_RESULT_ID,N_BID_FAIL_TYPE_ID
    FROM
        (
            SELECT A.BID_RESULT_ID
            ,CASE 
             WHEN A.CREATED_AT IS NULL THEN '오류'
             WHEN A.CREATED_AT+1 >= SYSDATE THEN '안전'
             WHEN A.CREATED_AT+1 < SYSDATE THEN '마감'
             ELSE '오류'
             END AS CREATED_AT
            FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_WINNING_PAYMENT B
            ON A.BID_RESULT_ID = B.BID_RESULT_ID
            LEFT JOIN BID_FAILURE_HISTORY C
            ON A.BID_RESULT_ID = C.BID_RESULT_ID
            WHERE B.BID_RESULT_ID IS NULL AND C.BID_RESULT_ID IS NULL
        )M
    WHERE M.CREATED_AT = '마감';


    SELECT NVL(PENALTY_TYPE_ID,0) INTO N_PENALTY_TYPE_ID
    FROM PENALTY_ASSIGN_TYPE
    WHERE PENALTY_TYPE_NAME = '자동';

    IF(N_PENALTY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20111,'패널티 분류 코드명에 "자동"인 코드명이 존재하지 않습니다');
    END IF;


    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    
    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;
    
    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;
    

    -- 패널티 입력(대기)
    INSERT INTO PENALTY_HISTORY(PENALTY_ID,USER_ID,PENALTY_TYPE_ID,ADMIN_ACCOUNT_ID,PENALTY_SCORE)
    SELECT PENALTY_SEQ.NEXTVAL,C.USER_ID,N_PENALTY_TYPE_ID,NULL,1
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     LEFT JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE D.MONEY_ID IS NULL;

    -- 구매자 보증금 환급 이력(수정 : 환급 -> 몰수)
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
     SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,C.USER_ID,N_MONEY_TYPE_ID,C.AUCTION_ID,0
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     INNER JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
     LEFT JOIN MONEY_TRANSACTION_HISTORY E
     ON C.AUCTION_ID = E.AUCTION_ID AND C.USER_ID = E.USER_ID
     AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE E.MONEY_ID IS NULL;

     -- 실구매자 이외 구매자 환급 이력(대기)
    -- INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    -- ,AUCTION_ID,AMOUNT)
    -- SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,A.USER_ID,N_MONEY_TYPE_ID2,A.AUCTION_ID,D.AMOUNT
    --  FROM AUCTION_BID_PARTICIPATION A LEFT JOIN AUCTION_WINNING_RESULT B
    --  ON A.BID_ID = B.BID_ID
    --  LEFT JOIN BID_FAILURE_HISTORY C
    --  ON B.BID_RESULT_ID = C.BID_RESULT_ID
    --  LEFT JOIN MONEY_TRANSACTION_HISTORY D
    --  ON A.USER_ID = D.USER_ID AND A.AUCTION_ID = D.AUCTION_ID
    --  AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
    --  LEFT JOIN MONEY_TRANSACTION_HISTORY E
    --  ON A.USER_ID = E.USER_ID AND A.AUCTION_ID = E.AUCTION_ID
    --  AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    --  WHERE B.BID_ID IS NULL
    --  AND E.MONEY_TYPE_ID IS NULL
    --  AND C;

     -- 실구매자 이외 구매자 환급 이력
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT)
    SELECT 
    MONEY_TRANSACTION_SEQ.NEXTVAL
    ,A.USER_ID
    ,N_MONEY_TYPE_ID2       -- 구매 보증금 환급
    ,A.AUCTION_ID
    ,D.AMOUNT
    FROM AUCTION_BID_PARTICIPATION A
-- 보증금 납부 이력 (환급 금액 가져오기)
    INNER JOIN MONEY_TRANSACTION_HISTORY D
    ON A.USER_ID = D.USER_ID 
    AND A.AUCTION_ID = D.AUCTION_ID
    AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID1  -- 구매 보증금 납부
-- 아직 환급 안 된 사람만
    LEFT JOIN MONEY_TRANSACTION_HISTORY E
    ON A.USER_ID = E.USER_ID 
    AND A.AUCTION_ID = E.AUCTION_ID
    AND E.MONEY_TYPE_ID = N_MONEY_TYPE_ID2  -- 구매 보증금 환급
-- 낙찰 실패가 발생한 경매인지 확인
    WHERE A.AUCTION_ID IN (
    SELECT BP.AUCTION_ID
    FROM AUCTION_BID_PARTICIPATION BP
    INNER JOIN AUCTION_WINNING_RESULT WR ON BP.BID_ID = WR.BID_ID
    INNER JOIN BID_FAILURE_HISTORY FH ON WR.BID_RESULT_ID = FH.BID_RESULT_ID
    )
    -- 실구매자(낙찰자) 제외
    AND A.BID_ID NOT IN (
    SELECT WR2.BID_ID
    FROM AUCTION_WINNING_RESULT WR2
    INNER JOIN BID_FAILURE_HISTORY FH2 ON WR2.BID_RESULT_ID = FH2.BID_RESULT_ID
    )
    AND E.MONEY_ID IS NULL;
    
    
    -- 판매자 보증금 몰수(수정: 몰수 -> 환급)
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,E.USER_ID,N_MONEY_TYPE_ID4,C.AUCTION_ID,F.AMOUNT
    FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
    ON A.BID_RESULT_ID = B.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION C
    ON B.BID_ID = C.BID_ID
    INNER JOIN AUCTION_REGISTRATION D
    ON C.AUCTION_ID = D.AUCTION_ID
    INNER JOIN PRODUCT E
    ON D.PRODUCT_ID = E.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY F
    ON E.USER_ID = F.USER_ID AND F.AUCTION_ID = D.AUCTION_ID
    AND F.MONEY_TYPE_ID = N_MONEY_TYPE_ID3
    LEFT JOIN MONEY_TRANSACTION_HISTORY G
    ON E.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID4
    WHERE G.MONEY_ID IS NULL;
    
    COMMIT;
    
    EXCEPTION
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
    
END;


-- 구매 확정 자동 처리 스케줄러(컴파일O,테스트X)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_AUTO_PURCHASE_CONFIRM'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_AUTO_PURCHASE_CONFIRM'
        ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
        ,ENABLED => FALSE
    );
END;

-- 구매 확정 자동 처리 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_AUTO_PURCHASE_CONFIRM
IS
    N_MONEY_TYPE_ID1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID5 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID6 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
BEGIN

    -- 구매 확정 이력
    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    SELECT PURCHASE_CONFIRM_SEQ.NEXTVAL,M.SHIPPING_ID
    FROM
        (
            SELECT A.SHIPPING_ID
            FROM DELIVERY_COMPLETED A LEFT JOIN PURCHASE_CONFIRM_HISTORY B
            ON A.SHIPPING_ID = B.SHIPPING_ID
            WHERE B.SHIPPING_ID IS NULL
            AND A.CREATED_AT+3 < SYSDATE
        )M;

    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID5
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID6
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금';
    
    IF(N_MONEY_TYPE_ID2 = 0)
        THEN RAISE_APPLICATION_ERROR(-20107,'머니 분류 테이블에 "구매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID1 = 0)
        THEN RAISE_APPLICATION_ERROR(-20108,'머니 분류 테이블에 "구매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID4 = 0)
        THEN RAISE_APPLICATION_ERROR(-20109,'머니 분류 테이블에 "판매 보증금 납부" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID3 = 0)
        THEN RAISE_APPLICATION_ERROR(-20110,'머니 분류 테이블에 "판매 보증금 환급" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID5 = 0)
        THEN RAISE_APPLICATION_ERROR(-20112,'머니 분류 테이블에 "결제" 코드명이 존재하지 않습니다');
    END IF;

    IF(N_MONEY_TYPE_ID6 = 0)
        THEN RAISE_APPLICATION_ERROR(-20113,'머니 분류 테이블에 "결제 대금" 코드명이 존재하지 않습니다');
    END IF;

    -- 구매 보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,F.USER_ID,N_MONEY_TYPE_ID1,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON F.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID2
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID1
    WHERE H.MONEY_ID IS NULL;
    -- GROUP BY F.USER_ID
    
    -- 판매보증금 환급
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,J.USER_ID,N_MONEY_TYPE_ID3,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN AUCTION_REGISTRATION I
    ON F.AUCTION_ID = I.AUCTION_ID
    INNER JOIN PRODUCT J
    ON I.PRODUCT_ID = J.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON J.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID4
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID3
    WHERE H.MONEY_ID IS NULL;
    
    -- 구매대금 판매자에게 이력추가
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_TRANSACTION_SEQ.NEXTVAL,J.USER_ID,N_MONEY_TYPE_ID6,F.AUCTION_ID,G.AMOUNT
    FROM PURCHASE_CONFIRM_HISTORY A 
    INNER JOIN DELIVERY_COMPLETED C
    ON A.SHIPPING_ID = C.SHIPPING_ID
    INNER JOIN AUCTION_WINNING_PAYMENT D
    ON C.PAYMENT_ID = D.PAYMENT_ID
    INNER JOIN AUCTION_WINNING_RESULT E
    ON D.BID_RESULT_ID = E.BID_RESULT_ID
    INNER JOIN AUCTION_BID_PARTICIPATION F
    ON E.BID_ID = F.BID_ID
    INNER JOIN AUCTION_REGISTRATION I
    ON F.AUCTION_ID = I.AUCTION_ID
    INNER JOIN PRODUCT J
    ON I.PRODUCT_ID = J.PRODUCT_ID
    INNER JOIN MONEY_TRANSACTION_HISTORY G
    ON F.USER_ID = G.USER_ID AND F.AUCTION_ID = G.AUCTION_ID
    AND G.MONEY_TYPE_ID = N_MONEY_TYPE_ID5
    LEFT JOIN MONEY_TRANSACTION_HISTORY H
    ON H.USER_ID = G.USER_ID AND H.AUCTION_ID = G.AUCTION_ID
    AND H.MONEY_TYPE_ID = N_MONEY_TYPE_ID6
    WHERE H.MONEY_ID IS NULL;
    
    -- 구매 확정 이력
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    SELECT TRANSACTION_SEQ.NEXTVAL,A.PURCHASE_CONFIRM_ID
    FROM PURCHASE_CONFIRM_HISTORY A LEFT JOIN TRANSACTION_COMPLETED B
    ON A.PURCHASE_CONFIRM_ID = B.PURCHASE_CONFIRM_ID
    WHERE B.TRANSACTION_ID IS NULL;

    COMMIT;

    EXCEPTION
    WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;


BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_DELETED_USER_CLEANUP'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_DELETED_USER_CLEANUP' 
        ,REPEAT_INTERVAL => 'FREQ=DAILY; BYHOUR=0'
        ,ENABLED => FALSE
    );
END;


-- 탈퇴 회원 정리 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_DELETED_USER_CLEANUP
IS
    N_ACCOUNT_EVENT_TYPE_ID ACCOUNT_EVENT_TYPE.ACCOUNT_EVENT_TYPE_ID%TYPE;
BEGIN
    SELECT NVL(ACCOUNT_EVENT_TYPE_ID,0) INTO N_ACCOUNT_EVENT_TYPE_ID
    FROM ACCOUNT_EVENT_TYPE
    WHERE EVENT_NAME = '탈퇴';

    IF(N_ACCOUNT_EVENT_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이없습니다');
    END IF;
    
    DELETE 
    FROM DELETED_USER A
    WHERE EXISTS
    (SELECT 1
    FROM ACCOUNT_EVENT_HISTORY B
    WHERE A.USER_ID = B.USER_ID
    AND B.ACCOUNT_EVENT_TYPE_ID = N_ACCOUNT_EVENT_TYPE_ID
    AND ADD_MONTHS(B.CREATED_AT,3) < SYSDATE  
    );
    
    COMMIT;
    EXCEPTION
        WHEN OTHERS
        THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
        RAISE_APPLICATION_ERROR(-20099,'실패');
END;


